#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""200語レベルの長文テキストを追加するスクリプト"""
import json

TEXTS_PATH = '/Users/kotai/Documents/Developpement/German/data/texts.json'

def N(s,l,j,f,c=None,num=None,g=None):
    t={"surface":s,"pos":"noun","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c: t["case"]=c
    if num: t["number"]=num
    if g: t["gender"]=g
    return t
def A(s,l,j,f,c=None,num=None,g=None):
    t={"surface":s,"pos":"article","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c: t["case"]=c
    if num: t["number"]=num
    if g: t["gender"]=g
    return t
def V(s,l,j,f,p=None):
    t={"surface":s,"pos":"verb","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if p: t["person"]=p
    return t
def J(s,l,j,f,c=None,num=None,g=None):
    t={"surface":s,"pos":"adjective","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c: t["case"]=c
    if num: t["number"]=num
    if g: t["gender"]=g
    return t
def P(s,l,j,f): return {"surface":s,"pos":"preposition","lemma":l,"meaning_ja":j,"meaning_fr":f}
def K(s,l,j,f): return {"surface":s,"pos":"conjunction","lemma":l,"meaning_ja":j,"meaning_fr":f}
def R(s,l,j,f): return {"surface":s,"pos":"adverb","lemma":l,"meaning_ja":j,"meaning_fr":f}
def Q(s,l,j,f,**kw):
    t={"surface":s,"pos":"pronoun","lemma":l,"meaning_ja":j,"meaning_fr":f}
    t.update(kw); return t
def E(s,j,f): return {"surface":s,"pos":"proper_noun","lemma":s,"meaning_ja":j,"meaning_fr":f}
def NUM(s,j,f): return {"surface":s,"pos":"number","lemma":s,"meaning_ja":j,"meaning_fr":f}
def pct(s="."): return {"surface":s,"pos":"punct"}

LONG_TEXTS = [

# ════════════════════════════════════════════════════════════
# t100 — Die Französische Revolution (~200 Wörter)
# ════════════════════════════════════════════════════════════
{
"id":"t100","title":"Die Französische Revolution",
"subtitle":"Freiheit, Gleichheit, Brüderlichkeit",
"level":"B2","category":"Geschichte",
"tokens":[
A("Die","die","その","la",c="nom",num="sg",g="f"),
J("Französische","französisch","フランスの","française",c="nom",num="sg",g="f"),
N("Revolution","Revolution","革命","révolution",c="nom",num="sg",g="f"),
V("war","sein","であった","était",p="3sg"),
N("eines","eines","一つ","l'un",c="nom",num="sg",g="n"),
A("der","der","の","des",c="gen",num="pl"),
J("bedeutendsten","bedeutend","最も重要な","plus importants",c="gen",num="pl"),
J("politischen","politisch","政治的な","politiques",c="gen",num="pl"),
N("Ereignisse","Ereignis","出来事","événements",c="gen",num="pl",g="n"),
A("der","der","の","de l'",c="gen",num="sg",g="f"),
J("europäischen","europäisch","ヨーロッパの","européenne",c="gen",num="sg",g="f"),
N("Geschichte","Geschichte","歴史","histoire",c="gen",num="sg",g="f"),
K("und","und","そして","et"),
V("dauerte","dauern","続いた","dura",p="3sg"),
P("von","von","〜から","de"),
NUM("1789","1789年","1789"),
P("bis","bis","〜まで","jusqu'en"),
NUM("1799","1799年","1799"),
pct("."),
Q("Ihre","ihr","その","ses",case="nom",number="pl"),
N("Ursachen","Ursache","原因","causes",c="nom",num="pl",g="f"),
V("waren","sein","〜であった","étaient",p="3pl"),
J("vielfältig","vielfältig","多様な","multiples"),
pct(":"),
A("Eine","ein","一つの","une",c="nom",num="sg",g="f"),
J("schwere","schwer","深刻な","grave",c="nom",num="sg",g="f"),
N("Finanzkrise","Finanzkrise","財政危機","crise financière",c="nom",num="sg",g="f"),
A("des","der","の","de l'",c="gen",num="sg",g="m"),
N("Staates","Staat","国家の","État",c="gen",num="sg",g="m"),
pct(","),
J("extreme","extrem","極端な","extrême",c="nom",num="sg",g="f"),
J("soziale","sozial","社会的な","sociale",c="nom",num="sg",g="f"),
N("Ungleichheit","Ungleichheit","不平等","inégalité",c="nom",num="sg",g="f"),
P("zwischen","zwischen","〜の間の","entre"),
A("dem","der","その","la",c="dat",num="sg",g="m"),
J("privilegierten","privilegiert","特権的な","privilégiée",c="dat",num="sg",g="m"),
N("Adel","Adel","貴族","noblesse",c="dat",num="sg",g="m"),
K("und","und","と","et"),
A("dem","der","その","le",c="dat",num="sg",g="m"),
J("verarmten","verarmt","貧しい","appauvri",c="dat",num="sg",g="m"),
J("dritten","dritt","第三の","troisième",c="dat",num="sg",g="m"),
N("Stand","Stand","身分","tiers état",c="dat",num="sg",g="m"),
K("sowie","sowie","また","ainsi que"),
A("die","die","その","les",c="acc",num="pl"),
J("revolutionären","revolutionär","革命的な","révolutionnaires",c="acc",num="pl"),
N("Ideen","Idee","思想","idées",c="acc",num="pl",g="f"),
A("der","der","の","des",c="gen",num="sg",g="f"),
N("Aufklärung","Aufklärung","啓蒙思想","Lumières",c="gen",num="sg",g="f"),
V("schufen","schaffen","生み出した","créèrent",p="3pl"),
A("den","der","その","le",c="acc",num="sg",g="m"),
N("Nährboden","Nährboden","温床","terreau",c="acc",num="sg",g="m"),
P("für","für","のための","pour"),
A("den","der","その","l'",c="acc",num="sg",g="m"),
N("Aufstand","Aufstand","蜂起","soulèvement",c="acc",num="sg",g="m"),
pct("."),
P("Am","an","〜に","le"),
NUM("14.","14日","14"),
N("Juli","Juli","7月","juillet",c="dat",num="sg",g="m"),
NUM("1789","1789年","1789"),
V("stürmten","stürmen","急襲した","prirent d'assaut",p="3pl"),
J("aufständische","aufständisch","反乱の","insurgés",c="nom",num="pl"),
N("Bürger","Bürger","市民","citoyens",c="nom",num="pl",g="m"),
A("die","die","その","la",c="acc",num="sg",g="f"),
E("Bastille","バスティーユ","Bastille"),
pct(","),
A("das","das","その","symbole de la",c="acc",num="sg",g="n"),
N("Symbol","Symbol","象徴","",c="acc",num="sg",g="n"),
A("der","der","の","de l'",c="gen",num="sg",g="f"),
J("königlichen","königlich","王の","royale",c="gen",num="sg",g="f"),
N("Willkürherrschaft","Willkürherrschaft","専制支配","tyrannie",c="gen",num="sg",g="f"),
P("in","in","〜の","à"),
E("Paris","パリ","Paris"),
pct("."),
Q("Dieses","dieser","この","cet",case="nom",number="sg",gender="n"),
N("Ereignis","Ereignis","出来事","événement",c="nom",num="sg",g="n"),
V("markiert","markieren","示す","marque",p="3sg"),
A("den","der","その","le",c="acc",num="sg",g="m"),
J("symbolischen","symbolisch","象徴的な","symbolique",c="acc",num="sg",g="m"),
N("Beginn","Beginn","始まり","début",c="acc",num="sg",g="m"),
A("der","der","の","de la",c="gen",num="sg",g="f"),
N("Revolution","Revolution","革命","révolution",c="gen",num="sg",g="f"),
pct("."),
R("Kurz","kurz","間もなく","peu"),
R("darauf","darauf","その後すぐ","après"),
V("verabschiedete","verabschieden","採択した","adopta",p="3sg"),
A("die","die","その","l'",c="nom",num="sg",g="f"),
N("Nationalversammlung","Nationalversammlung","国民議会","Assemblée nationale",c="nom",num="sg",g="f"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Erklärung","Erklärung","宣言","Déclaration",c="acc",num="sg",g="f"),
A("der","der","の","des",c="gen",num="pl"),
N("Menschen","Mensch","人間の","droits de l'homme",c="gen",num="pl",g="m"),
K("und","und","と","et"),
N("Bürgerrechte","Bürgerrecht","市民権","droits du citoyen",c="gen",num="pl",g="n"),
pct(","),
A("die","die","〜という","qui",c="nom",num="sg",g="f"),
J("grundlegende","grundlegend","基本的な","fondamentales",c="acc",num="pl"),
N("Freiheiten","Freiheit","自由（複数）","libertés",c="acc",num="pl",g="f"),
K("und","und","と","et"),
A("die","die","その","l'",c="acc",num="sg",g="f"),
N("Gleichheit","Gleichheit","平等","égalité",c="acc",num="sg",g="f"),
J("aller","aller","すべての","de tous les",c="gen",num="pl"),
N("Bürger","Bürger","市民","citoyens",c="gen",num="pl",g="m"),
P("vor","vor","の前で","devant"),
A("dem","der","その","la",c="dat",num="sg",g="n"),
N("Gesetz","Gesetz","法律","loi",c="dat",num="sg",g="n"),
V("proklamierte","proklamieren","宣言した","proclama",p="3sg"),
pct("."),
P("In","in","〜で","Dans"),
A("der","der","その","la",c="dat",num="sg",g="f"),
J("radikalen","radikal","急進的な","radicale",c="dat",num="sg",g="f"),
N("Phase","Phase","局面","phase",c="dat",num="sg",g="f"),
P("unter","unter","〜の下で","sous"),
E("Robespierre","ロベスピエール","Robespierre"),
pct(","),
A("der","der","の","de la soi-disant",c="gen",num="sg",g="f"),
J("sogenannten","sogenannt","いわゆる","",c="gen",num="sg",g="f"),
N("Schreckensherrschaft","Schreckensherrschaft","恐怖政治","Terreur",c="gen",num="sg",g="f"),
P("von","von","〜から","de"),
NUM("1793","1793年","1793"),
P("bis","bis","〜まで","à"),
NUM("1794","1794年","1794"),
pct(","),
V("wurden","werden","〜された","furent",p="3pl"),
N("Tausende","Tausend","何千もの","des milliers",c="nom",num="pl",g="n"),
P("von","von","の","de"),
J("politischen","politisch","政治的な","politiques",c="dat",num="pl"),
N("Gegnern","Gegner","反対者","adversaires",c="dat",num="pl",g="m"),
V("hingerichtet","hinrichten","処刑された","exécutés"),
pct("."),
A("Die","die","その","la",c="nom",num="sg",g="f"),
N("Guillotine","Guillotine","ギロチン","guillotine",c="nom",num="sg",g="f"),
V("wurde","werden","〜になった","devint",p="3sg"),
P("zum","zu","〜の","le"),
N("Symbol","Symbol","象徴","symbole",c="dat",num="sg",g="n"),
Q("dieser","dieser","この","de cette",case="gen",number="sg",gender="f"),
J("blutigen","blutig","血塗られた","sanglante",c="gen",num="sg",g="f"),
N("Epoche","Epoche","時代","époque",c="gen",num="sg",g="f"),
pct("."),
R("Schließlich","schließlich","最終的に","finalement"),
V("endete","enden","終わった","prit fin",p="3sg"),
A("die","die","その","la",c="nom",num="sg",g="f"),
N("Terrorherrschaft","Terrorherrschaft","恐怖政治","Terreur",c="nom",num="sg",g="f"),
P("mit","mit","〜と共に","avec"),
A("der","der","その","l'",c="dat",num="sg",g="f"),
N("Verhaftung","Verhaftung","逮捕","arrestation",c="dat",num="sg",g="f"),
K("und","und","と","et"),
N("Hinrichtung","Hinrichtung","処刑","exécution",c="dat",num="sg",g="f"),
E("Robespierres","ロベスピエールの","de Robespierre"),
R("selbst","selbst","自ら","lui-même"),
pct("."),
P("Nach","nach","〜の後に","Après"),
A("einer","ein","一つの","une",c="dat",num="sg",g="f"),
N("Phase","Phase","局面","phase",c="dat",num="sg",g="f"),
A("der","der","の","d'",c="gen",num="sg",g="f"),
N("Instabilität","Instabilität","不安定","instabilité",c="gen",num="sg",g="f"),
V("ergriff","ergreifen","掌握した","s'empara de",p="3sg"),
E("Napoleon Bonaparte","ナポレオン・ボナパルト","Napoléon Bonaparte"),
A("die","die","その","le",c="acc",num="sg",g="f"),
N("Macht","Macht","権力","pouvoir",c="acc",num="sg",g="f"),
K("und","und","そして","et"),
V("errichtete","errichten","設立した","établit",p="3sg"),
A("das","das","その","le",c="acc",num="sg",g="n"),
N("Konsulat","Konsulat","統領政府","Consulat",c="acc",num="sg",g="n"),
pct(","),
K("bevor","bevor","〜する前に","avant de"),
Q("er","er","彼は","se"),
Q("sich","sich","自分自身を",""),
P("zum","zu","〜に","en"),
N("Kaiser","Kaiser","皇帝","empereur",c="dat",num="sg",g="m"),
V("krönte","krönen","戴冠させた","couronner",p="3sg"),
pct("."),
A("Das","das","その","le",c="nom",num="sg",g="n"),
J("bleibende","bleibend","永続する","durable",c="nom",num="sg",g="n"),
N("Erbe","Erbe","遺産","héritage",c="nom",num="sg",g="n"),
A("der","der","の","de la",c="gen",num="sg",g="f"),
J("Französischen","französisch","フランスの","française",c="gen",num="sg",g="f"),
N("Revolution","Revolution","革命","révolution",c="gen",num="sg",g="f"),
V("liegt","liegen","ある","réside",p="3sg"),
P("in","in","〜の中に","dans"),
A("den","der","その","les",c="dat",num="pl"),
N("Ideen","Idee","理念","idées",c="dat",num="pl",g="f"),
A("der","der","の","de la",c="gen",num="sg",g="f"),
N("Volkssouveränität","Volkssouveränität","国民主権","souveraineté populaire",c="gen",num="sg",g="f"),
K("und","und","と","et"),
A("der","der","の","de l'",c="gen",num="sg",g="f"),
J("staatsbürgerlichen","staatsbürgerlich","公民の","civique",c="gen",num="sg",g="f"),
N("Gleichheit","Gleichheit","平等","égalité",c="gen",num="sg",g="f"),
pct(","),
A("die","die","〜という","qui",c="nom",num="pl"),
J("politische","politisch","政治的な","politiques",c="acc",num="pl"),
N("Bewegungen","Bewegung","運動","mouvements",c="acc",num="pl",g="f"),
P("in","in","〜で","dans"),
J("ganz","ganz","全","toute",c="dat",num="sg"),
E("Europa","ヨーロッパ","Europe"),
K("und","und","と","et"),
A("der","der","の","du",c="gen",num="sg",g="f"),
N("Welt","Welt","世界","monde",c="gen",num="sg",g="f"),
P("über","über","〜以上","pendant des"),
N("Jahrhunderte","Jahrhundert","世紀","siècles",c="acc",num="pl",g="n"),
V("beeinflussten","beeinflussen","影響を与えた","ont influencé",p="3pl"),
pct("."),
]},

# ════════════════════════════════════════════════════════════
# t101 — Kants kategorischer Imperativ (~200 Wörter)
# ════════════════════════════════════════════════════════════
{
"id":"t101","title":"Kants kategorischer Imperativ",
"subtitle":"Vernunft als Grundlage der Moral",
"level":"C1","category":"Philosophie",
"tokens":[
E("Immanuel Kant","イマヌエル・カント","Immanuel Kant"),
pct(","),
A("einer","ein","〜の中の一人","l'un des",c="nom",num="sg",g="m"),
A("der","der","の","plus grands",c="gen",num="pl"),
J("bedeutendsten","bedeutend","最も重要な","",c="gen",num="pl"),
N("Philosophen","Philosoph","哲学者","philosophes",c="gen",num="pl",g="m"),
A("der","der","の","des",c="gen",num="sg",g="f"),
N("Aufklärung","Aufklärung","啓蒙主義","Lumières",c="gen",num="sg",g="f"),
pct(","),
V("entwickelte","entwickeln","発展させた","développa",p="3sg"),
A("eine","ein","一つの","une",c="acc",num="sg",g="f"),
J("revolutionäre","revolutionär","革命的な","révolutionnaire",c="acc",num="sg",g="f"),
N("Moralphilosophie","Moralphilosophie","道徳哲学","philosophie morale",c="acc",num="sg",g="f"),
pct(","),
A("die","die","〜という","qui",c="nom",num="sg",g="f"),
R("nicht","nicht","ではなく","ne repose pas sur"),
P("auf","auf","〜に",""),
N("Gefühlen","Gefühl","感情","sentiments",c="dat",num="pl",g="n"),
K("oder","oder","または","ni"),
N("Neigungen","Neigung","傾向・感情","inclinations",c="dat",num="pl",g="f"),
pct(","),
K("sondern","sondern","しかし","mais"),
R("allein","allein","ただ〜のみ","uniquement"),
P("auf","auf","〜に基づく","sur"),
A("der","der","その","la",c="dat",num="sg",g="f"),
N("Vernunft","Vernunft","理性","raison",c="dat",num="sg",g="f"),
V("beruht","beruhen","基づく","repose",p="3sg"),
pct("."),
A("Das","das","その","le",c="nom",num="sg",g="n"),
N("Herzstück","Herzstück","核心","cœur",c="nom",num="sg",g="n"),
Q("seiner","sein","彼の","de sa",case="gen",number="sg",gender="f"),
N("Ethik","Ethik","倫理学","éthique",c="gen",num="sg",g="f"),
V("ist","sein","〜である","est",p="3sg"),
A("der","der","その","l'",c="nom",num="sg",g="m"),
J("kategorische","kategorisch","定言的な","catégorique",c="nom",num="sg",g="m"),
N("Imperativ","Imperativ","命令法","impératif",c="nom",num="sg",g="m"),
pct("."),
Q("Seine","sein","彼の","sa",case="nom",number="sg",gender="f"),
J("bekannteste","bekannt","最もよく知られた","plus connue",c="nom",num="sg",g="f"),
N("Formel","Formel","定式","formule",c="nom",num="sg",g="f"),
V("lautet","lauten","述べる","dit",p="3sg"),
pct(":"),
V("Handle","handeln","行為せよ","agis",p="2sg"),
R("nur","nur","ただ〜のみ","seulement"),
P("nach","nach","〜に従って","selon"),
Q("derjenigen","derjenige","その","la",case="dat",number="sg",gender="f"),
N("Maxime","Maxime","格率","maxime",c="dat",num="sg",g="f"),
pct(","),
P("durch","durch","〜によって","par laquelle"),
A("die","die","その","tu",c="acc",num="sg",g="f"),
Q("du","du","あなたは","peux"),
R("zugleich","zugleich","同時に","en même temps"),
V("wollen","wollen","望む","vouloir"),
V("kannst","können","できる","",p="2sg"),
pct(","),
K("dass","dass","〜ということ","qu'"),
Q("sie","sie","それが","elle"),
A("ein","ein","一つの","une",c="nom",num="sg",g="n"),
J("allgemeines","allgemein","普遍的な","universelle",c="nom",num="sg",g="n"),
N("Gesetz","Gesetz","法則","loi",c="nom",num="sg",g="n"),
V("werde","werden","〜となる","devienne"),
pct("."),
Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
N("Formel","Formel","定式","formule",c="nom",num="sg",g="f"),
V("verlangt","verlangen","要求する","exige",p="3sg"),
pct(","),
K("dass","dass","〜ということ","que"),
Q("wir","wir","私たちは","nous"),
Q("unsere","unser","私たちの","nos",case="acc",number="pl"),
N("Handlungsprinzipien","Handlungsprinzip","行動原則","principes d'action",c="acc",num="pl",g="n"),
P("auf","auf","〜について","à l'aune de"),
Q("ihre","ihr","それらの","leur",case="acc",number="sg",gender="f"),
N("Verallgemeinerbarkeit","Verallgemeinerbarkeit","普遍化可能性","universalisabilité",c="acc",num="sg",g="f"),
V("prüfen","prüfen","検討する","évaluons"),
pct(":"),
V("Wäre","sein","であろうか","le monde serait-il bon"),
A("die","die","その","",c="nom",num="sg",g="f"),
N("Welt","Welt","世界","",c="nom",num="sg",g="f"),
J("gut","gut","良い","si"),
pct(","),
K("wenn","wenn","もし〜なら","tous agissaient"),
J("alle","aller","すべての","",c="nom",num="pl"),
R("so","so","そのように","comme moi"),
V("handelten","handeln","行動した","",p="3pl"),
K("wie","wie","〜のように",""),
Q("ich","ich","私が","moi"),
pct("?"),
A("Eine","ein","一つの","une",c="nom",num="sg",g="f"),
J("weitere","weit","さらなる","autre",c="nom",num="sg",g="f"),
J("wichtige","wichtig","重要な","formulation importante",c="nom",num="sg",g="f"),
N("Formulierung","Formulierung","定式化","",c="nom",num="sg",g="f"),
V("ist","sein","〜である","est",p="3sg"),
A("die","die","その","la",c="nom",num="sg",g="f"),
N("Menschheitszweck-Formel","Menschheitszweck-Formel","人類目的定式","formule de l'humanité",c="nom",num="sg",g="f"),
pct(":"),
V("Handle","handeln","行為せよ","agis",p="2sg"),
R("so","so","そのように","de sorte"),
pct(","),
K("dass","dass","〜ということ","que"),
Q("du","du","あなたは","tu"),
A("die","die","その","l'",c="acc",num="sg",g="f"),
N("Menschheit","Menschheit","人類","humanité",c="acc",num="sg",g="f"),
R("niemals","niemals","決して〜ない","jamais"),
R("bloß","bloß","単に","simplement"),
P("als","als","〜として","comme"),
N("Mittel","Mittel","手段","moyen",c="acc",num="sg",g="n"),
pct(","),
K("sondern","sondern","しかし","mais"),
R("jederzeit","jederzeit","常に","toujours"),
R("zugleich","zugleich","同時に","aussi"),
P("als","als","〜として","comme"),
N("Zweck","Zweck","目的","fin",c="acc",num="sg",g="m"),
V("brauchst","brauchen","使う","traites",p="2sg"),
pct("."),
Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
N("Formel","Formel","定式","formule",c="nom",num="sg",g="f"),
V("schützt","schützen","保護する","protège",p="3sg"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Würde","Würde","尊厳","dignité",c="acc",num="sg",g="f"),
J("jedes","jeder","あらゆる","de chaque",c="gen",num="sg",g="m"),
N("Menschen","Mensch","人間","être humain",c="gen",num="sg",g="m"),
K("und","und","そして","et"),
V("verbietet","verbieten","禁じる","interdit",p="3sg"),
Q("es","es","それを","de"),
pct(","),
J("andere","ander","他の","d'autres",c="acc",num="pl"),
N("Menschen","Mensch","人間","êtres humains",c="acc",num="pl",g="m"),
P("als","als","〜として","comme de simples"),
J("bloße","bloß","単なる","simples",c="acc",num="pl"),
N("Werkzeuge","Werkzeug","道具","outils",c="acc",num="pl",g="n"),
P("zu","zu","〜するために","à"),
V("benutzen","benutzen","使う","utiliser"),
pct("."),
N("Kants","Kant","カントの","la philosophie de Kant",c="gen",num="sg",g="m"),
N("Ethik","Ethik","倫理学","éthique",c="nom",num="sg",g="f"),
V("hat","haben","〜した","a",p="3sg"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Philosophie","Philosophie","哲学","philosophie",c="acc",num="sg",g="f"),
pct(","),
A("das","das","その","le",c="acc",num="sg",g="n"),
N("Recht","Recht","法学","droit",c="acc",num="sg",g="n"),
K("und","und","と","et"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Menschenrechtsdiskussion","Menschenrechtsdiskussion","人権論","discussion sur les droits de l'homme",c="acc",num="sg",g="f"),
P("bis","bis","〜まで","jusqu'à"),
R("heute","heute","今日","aujourd'hui"),
R("nachhaltig","nachhaltig","持続的に","durablement"),
V("geprägt","prägen","形作った","marqué"),
pct("."),
]},

# ════════════════════════════════════════════════════════════
# t102 — Einsteins Relativitätstheorie (~200 Wörter)
# ════════════════════════════════════════════════════════════
{
"id":"t102","title":"Einsteins Relativitätstheorie",
"subtitle":"Raum, Zeit und die Krümmung der Welt",
"level":"C1","category":"Wissenschaft",
"tokens":[
E("Albert Einstein","アルベルト・アインシュタイン","Albert Einstein"),
pct(","),
V("geboren","gebären","生まれた","né"),
NUM("1879","1879年","1879"),
P("in","in","〜で","à"),
E("Ulm","ウルム","Ulm"),
pct(","),
V("revolutionierte","revolutionieren","革命を起こした","révolutionna",p="3sg"),
Q("unser","unser","私たちの","notre",case="acc",number="sg",gender="n"),
N("Verständnis","Verständnis","理解","compréhension",c="acc",num="sg",g="n"),
P("von","von","〜の","de"),
N("Raum","Raum","空間","l'espace",c="dat",num="sg",g="m"),
pct(","),
N("Zeit","Zeit","時間","le temps",c="dat",num="sg",g="f"),
K("und","und","と","et"),
N("Gravitation","Gravitation","重力","la gravitation",c="dat",num="sg",g="f"),
P("mit","mit","〜によって","avec"),
J("zwei","zwei","二つの","deux"),
J("grundlegenden","grundlegend","根本的な","fondamentales",c="dat",num="pl"),
N("Theorien","Theorie","理論","théories",c="dat",num="pl",g="f"),
pct(":"),
A("der","der","その","la",c="dat",num="sg",g="f"),
J("speziellen","speziell","特殊な","spéciale",c="dat",num="sg",g="f"),
K("und","und","と","et"),
A("der","der","その","la",c="dat",num="sg",g="f"),
J("allgemeinen","allgemein","一般の","générale",c="dat",num="sg",g="f"),
N("Relativitätstheorie","Relativitätstheorie","相対性理論","théorie de la relativité",c="dat",num="sg",g="f"),
pct("."),
P("Im","in","〜に","en"),
N("Jahr","Jahr","年","an",c="dat",num="sg",g="n"),
NUM("1905","1905年","1905"),
pct(","),
A("dem","der","その","l'",c="dat",num="sg",g="n"),
J("sogenannten","sogenannt","いわゆる","soi-disant",c="dat",num="sg",g="n"),
N("Wunderjahr","Wunderjahr","奇跡の年","année miraculeuse",c="dat",num="sg",g="n"),
pct(","),
V("veröffentlichte","veröffentlichen","発表した","publia",p="3sg"),
E("Einstein","アインシュタイン","Einstein"),
Q("seine","sein","彼の","sa",case="acc",number="sg",gender="f"),
J("spezielle","speziell","特殊な","spéciale",c="acc",num="sg",g="f"),
N("Relativitätstheorie","Relativitätstheorie","相対性理論","théorie de la relativité",c="acc",num="sg",g="f"),
pct("."),
Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
N("Theorie","Theorie","理論","théorie",c="nom",num="sg",g="f"),
V("beruht","beruhen","基づく","repose",p="3sg"),
P("auf","auf","〜に","sur"),
J("zwei","zwei","二つの","deux"),
N("Postulaten","Postulat","公理","postulats",c="dat",num="pl",g="n"),
pct(":"),
R("Erstens","erstens","第一に","premièrement"),
V("sind","sein","〜である","sont",p="3pl"),
A("die","die","その","les",c="nom",num="pl"),
N("Naturgesetze","Naturgesetz","自然法則","lois de la nature",c="nom",num="pl",g="n"),
P("in","in","〜で","dans"),
J("allen","aller","すべての","tous les",c="dat",num="pl"),
N("Inertialsystemen","Inertialsystem","慣性系","référentiels inertiels",c="dat",num="pl",g="n"),
J("gleich","gleich","同一の","identiques"),
pct(","),
K("und","und","そして","et"),
R("zweitens","zweitens","第二に","deuxièmement"),
V("ist","sein","〜である","est",p="3sg"),
A("die","die","その","la",c="nom",num="sg",g="f"),
N("Lichtgeschwindigkeit","Lichtgeschwindigkeit","光速","vitesse de la lumière",c="nom",num="sg",g="f"),
P("im","in","〜で","dans le"),
N("Vakuum","Vakuum","真空","vide",c="dat",num="sg",g="n"),
P("für","für","〜にとって","pour"),
J("alle","aller","すべての","tous les",c="acc",num="pl"),
N("Beobachter","Beobachter","観察者","observateurs",c="acc",num="pl",g="m"),
J("konstant","konstant","一定の","constante"),
pct("."),
P("Aus","aus","〜から","De"),
Q("diesen","dieser","これらの","ces",case="dat",number="pl"),
N("Postulaten","Postulat","公理","postulats",c="dat",num="pl",g="n"),
V("folgen","folgen","導かれる","découlent",p="3pl"),
J("verblüffende","verblüffend","驚くべき","stupéfiantes",c="nom",num="pl"),
N("Konsequenzen","Konsequenz","結果","conséquences",c="nom",num="pl",g="f"),
pct(":"),
V("Bewegt","bewegen","動く","si un objet se déplace",p="3sg"),
Q("sich","sich","自分が",""),
A("ein","ein","一つの","à grande vitesse"),
N("Objekt","Objekt","物体","",c="nom",num="sg",g="n"),
P("mit","mit","〜で",""),
J("hoher","hoch","高い","élevée",c="dat",num="sg",g="f"),
N("Geschwindigkeit","Geschwindigkeit","速度","vitesse",c="dat",num="sg",g="f"),
pct(","),
V("verlangsamt","verlangsamen","遅くなる","le temps se ralentit",p="3sg"),
Q("sich","sich","〜が",""),
P("für","für","〜にとって","pour"),
Q("dieses","dieser","この","cet",case="acc",number="sg",gender="n"),
N("Objekt","Objekt","物体","objet",c="acc",num="sg",g="n"),
A("die","die","その","le",c="nom",num="sg",g="f"),
N("Zeit","Zeit","時間","temps",c="nom",num="sg",g="f"),
pct(","),
A("ein","ein","〜という","un",c="nom",num="sg",g="n"),
N("Phänomen","Phänomen","現象","phénomène",c="nom",num="sg",g="n"),
pct(","),
A("das","das","〜という","connu sous le nom de",c="nom",num="sg",g="n"),
P("als","als","〜として",""),
N("Zeitdilatation","Zeitdilatation","時間の遅れ","dilatation du temps",c="nom",num="sg",g="f"),
V("bekannt","bekannt","知られている",""),
V("ist","sein","〜である","est",p="3sg"),
pct("."),
A("Die","die","その","la",c="nom",num="sg",g="f"),
J("wohl","wohl","おそらく","probablement"),
J("bekannteste","bekannt","最もよく知られた","plus célèbre",c="nom",num="sg",g="f"),
N("Gleichung","Gleichung","等式・式","équation",c="nom",num="sg",g="f"),
A("der","der","の","de la",c="gen",num="sg",g="f"),
N("Physik","Physik","物理学","physique",c="gen",num="sg",g="f"),
pct(","),
N("E=mc²","E=mc²","E=mc²","E=mc²"),
pct(","),
V("folgt","folgen","導かれる","résulte",p="3sg"),
R("ebenfalls","ebenfalls","同様に","également"),
P("aus","aus","〜から","de"),
Q("dieser","dieser","この","cette",case="dat",number="sg",gender="f"),
N("Theorie","Theorie","理論","théorie",c="dat",num="sg",g="f"),
K("und","und","そして","et"),
V("besagt","besagen","述べる","stipule",p="3sg"),
pct(","),
K("dass","dass","〜ということ","que"),
N("Masse","Masse","質量","masse",c="nom",num="sg",g="f"),
K("und","und","と","et"),
N("Energie","Energie","エネルギー","énergie",c="nom",num="sg",g="f"),
J("äquivalent","äquivalent","等価の","équivalentes"),
K("und","und","そして","et"),
J("ineinander","ineinander","互いに","l'une en l'autre"),
J("umwandelbar","umwandelbar","変換可能な","convertibles"),
V("sind","sein","〜である","sont",p="3pl"),
pct("."),
J("Zehn","zehn","10の","dix"),
N("Jahre","Jahr","年","ans",c="acc",num="pl",g="n"),
R("später","später","後に","plus tard"),
pct(","),
P("im","in","〜に","en"),
N("Jahr","Jahr","年","an",c="dat",num="sg",g="n"),
NUM("1915","1915年","1915"),
pct(","),
V("veröffentlichte","veröffentlichen","発表した","publia",p="3sg"),
E("Einstein","アインシュタイン","Einstein"),
A("die","die","その","la",c="acc",num="sg",g="f"),
J("allgemeine","allgemein","一般の","générale",c="acc",num="sg",g="f"),
N("Relativitätstheorie","Relativitätstheorie","相対性理論","théorie de la relativité",c="acc",num="sg",g="f"),
pct(","),
A("die","die","〜という","qui",c="nom",num="sg",g="f"),
N("Gravitation","Gravitation","重力","gravitation",c="acc",num="sg",g="f"),
R("nicht","nicht","〜でなく","non pas comme"),
P("als","als","〜として","une force"),
N("Kraft","Kraft","力","",c="acc",num="sg",g="f"),
pct(","),
K("sondern","sondern","しかし","mais comme"),
P("als","als","〜として",""),
N("Krümmung","Krümmung","曲がり・湾曲","courbure",c="acc",num="sg",g="f"),
A("der","der","の","de l'",c="gen",num="sg",g="f"),
N("Raumzeit","Raumzeit","時空","espace-temps",c="gen",num="sg",g="f"),
V("beschreibt","beschreiben","記述する","décrit",p="3sg"),
pct("."),
J("Massive","massiv","質量を持つ","Les objets massifs",c="nom",num="pl"),
N("Objekte","Objekt","物体","",c="nom",num="pl",g="n"),
P("wie","wie","〜のような","comme"),
N("Sterne","Stern","星","étoiles",c="nom",num="pl",g="m"),
K("und","und","と","et"),
J("schwarze","schwarz","黒の","trous noirs",c="nom",num="pl"),
N("Löcher","Loch","穴（複数）","",c="nom",num="pl",g="n"),
V("verbiegen","verbiegen","曲げる","courbent",p="3pl"),
A("die","die","その","l'",c="acc",num="sg",g="f"),
N("Raumzeit","Raumzeit","時空","espace-temps",c="acc",num="sg",g="f"),
P("um","um","〜の周りに","autour d'eux"),
Q("sich","sich","自分の周り",""),
R("herum","herum","周囲に",""),
pct(","),
K("und","und","そして","et"),
N("Licht","Licht","光","la lumière",c="nom",num="sg",g="n"),
V("folgt","folgen","従う","suit",p="3sg"),
Q("dieser","dieser","この","cette",case="dat",number="sg",gender="f"),
N("Krümmung","Krümmung","湾曲","courbure",c="dat",num="sg",g="f"),
pct("."),
Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
N("Vorhersage","Vorhersage","予測","prédiction",c="nom",num="sg",g="f"),
V("wurde","werden","〜された","fut",p="3sg"),
NUM("1919","1919年","1919"),
P("durch","durch","〜によって","par"),
A("die","die","その","l'",c="acc",num="sg",g="f"),
N("Beobachtung","Beobachtung","観測","observation",c="acc",num="sg",g="f"),
A("einer","ein","〜の","d'une",c="gen",num="sg",g="f"),
N("Sonnenfinsternis","Sonnenfinsternis","日食","éclipse solaire",c="gen",num="sg",g="f"),
V("bestätigt","bestätigen","確認された","confirmée"),
K("und","und","そして","et"),
V("machte","machen","〜した","rendit",p="3sg"),
E("Einstein","アインシュタイン","Einstein"),
J("weltberühmt","weltberühmt","世界的に有名な","mondialement célèbre"),
pct("."),
]},

# ════════════════════════════════════════════════════════════
# t103 — Franz Kafka: Leben und Werk (~200 Wörter)
# ════════════════════════════════════════════════════════════
{
"id":"t103","title":"Franz Kafka: Leben und Werk",
"subtitle":"Entfremdung und das Absurde",
"level":"C1","category":"Literatur",
"tokens":[
E("Franz Kafka","フランツ・カフカ","Franz Kafka"),
pct(","),
V("geboren","gebären","生まれた","né"),
NUM("1883","1883年","1883"),
P("in","in","〜で","à"),
E("Prag","プラハ","Prague"),
P("als","als","〜として","comme"),
N("Sohn","Sohn","息子","fils",c="nom",num="sg",g="m"),
A("einer","ein","〜の","d'une",c="gen",num="sg",g="f"),
J("deutschsprachigen","deutschsprachig","ドイツ語圏の","germanophone",c="gen",num="sg",g="f"),
J("jüdischen","jüdisch","ユダヤ系の","juive",c="gen",num="sg",g="f"),
N("Familie","Familie","家族","famille",c="gen",num="sg",g="f"),
pct(","),
V("gilt","gelten","見なされる","est considéré",p="3sg"),
P("als","als","〜として","comme"),
A("einer","ein","〜の中の一人","l'un des",c="nom",num="sg",g="m"),
A("der","der","の","plus influents",c="gen",num="pl"),
J("einflussreichsten","einflussreich","最も影響力のある","",c="gen",num="pl"),
N("Schriftsteller","Schriftsteller","作家","écrivains",c="gen",num="pl",g="m"),
A("des","der","の","du",c="gen",num="sg",g="n"),
NUM("20.","20","XX"),
N("Jahrhunderts","Jahrhundert","世紀の","siècle",c="gen",num="sg",g="n"),
pct("."),
Q("Er","er","彼は","il"),
V("schrieb","schreiben","書いた","écrivit",p="3sg"),
P("auf","auf","〜で","en"),
N("Deutsch","Deutsch","ドイツ語","allemand",c="dat",num="sg",g="n"),
P("in","in","〜に","dans"),
A("einer","ein","〜の","une",c="dat",num="sg",g="f"),
N("Zeit","Zeit","時代","époque",c="dat",num="sg",g="f"),
K("und","und","〜と","et"),
P("an","an","〜で","dans"),
A("einem","ein","〜の","un",c="dat",num="sg",g="m"),
N("Ort","Ort","場所","lieu",c="dat",num="sg",g="m"),
pct(","),
P("wo","wo","〜で","où"),
N("Deutsch","Deutsch","ドイツ語","l'allemand",c="nom",num="sg",g="n"),
pct(","),
N("Tschechisch","Tschechisch","チェコ語","le tchèque",c="nom",num="sg",g="n"),
K("und","und","と","et"),
N("Jiddisch","Jiddisch","イディッシュ語","le yiddish",c="nom",num="sg",g="n"),
J("nebeneinander","nebeneinander","並存して","côte à côte"),
V("existierten","existieren","存在した","coexistaient",p="3pl"),
pct("."),
N("Tagsüber","Tagsüber","日中","le jour"),
V("arbeitete","arbeiten","働いた","il travaillait",p="3sg"),
Q("er","er","彼は",""),
P("als","als","〜として","comme"),
N("Versicherungsbeamter","Versicherungsbeamte","保険会社員","fonctionnaire d'assurances",c="nom",num="sg",g="m"),
pct(","),
N("nachts","nachts","夜に","la nuit"),
V("schrieb","schreiben","書いた","il écrivait",p="3sg"),
Q("er","er","彼は",""),
Q("seine","sein","彼の","ses",case="acc",number="pl"),
N("Werke","Werk","作品","œuvres",c="acc",num="pl",g="n"),
pct(","),
P("von","von","〜の中で","dont"),
A("denen","der","それの","il"),
Q("er","er","彼は","laissa"),
J("viele","viele","多くの","beaucoup"),
P("zu","zu","〜に",""),
N("Lebzeiten","Lebzeiten","生前","de son vivant",c="dat",num="pl",g="n"),
J("unveröffentlicht","unveröffentlicht","未発表の","inédites"),
V("ließ","lassen","〜させた","",p="3sg"),
pct("."),
Q("Seine","sein","彼の","son",case="nom",number="sg",gender="f"),
N("Erzählung","Erzählung","物語・短編","nouvelle",c="nom",num="sg",g="f"),
pct("„"),
A("Die","die","その","La",c="nom",num="sg",g="f"),
N("Verwandlung","Verwandlung","変身","Métamorphose",c="nom",num="sg",g="f"),
pct("""),
P("von","von","〜の","de"),
NUM("1915","1915年","1915"),
V("beginnt","beginnen","始まる","commence",p="3sg"),
P("mit","mit","〜で","par"),
A("dem","der","その","la",c="dat",num="sg",g="m"),
J("berühmten","berühmt","有名な","célèbre",c="dat",num="sg",g="m"),
J("ersten","erst","最初の","première",c="dat",num="sg",g="m"),
N("Satz","Satz","文・文章","phrase",c="dat",num="sg",g="m"),
pct(":"),
P("Als","als","〜した時","Alors que"),
E("Gregor Samsa","グレーゴル・ザムザ","Gregor Samsa"),
A("eines","ein","ある","un",c="gen",num="sg",g="m"),
N("Morgens","Morgen","朝","matin",c="gen",num="sg",g="m"),
P("aus","aus","〜から",""),
J("unruhigen","unruhig","不安な","agités",c="dat",num="pl"),
N("Träumen","Traum","夢","rêves",c="dat",num="pl",g="m"),
V("erwachte","erwachen","目覚めた","s'éveilla",p="3sg"),
pct(","),
V("fand","finden","気づいた","il se trouva",p="3sg"),
Q("er","er","彼は",""),
Q("sich","sich","自分が",""),
P("in","in","〜で","dans"),
Q("seinem","sein","彼の","son",case="dat",number="sg",gender="n"),
N("Bett","Bett","ベッド","lit",c="dat",num="sg",g="n"),
P("zu","zu","〜に","transformé en"),
A("einem","ein","〜に","un",c="dat",num="sg",g="n"),
J("ungeheueren","ungeheuer","巨大な","énorme",c="dat",num="sg",g="n"),
N("Ungeziefer","Ungeziefer","害虫・虫","insecte",c="dat",num="sg",g="n"),
V("verwandelt","verwandeln","変身した",""),
pct("."),
Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
J("surreale","surreal","シュールな","surréaliste",c="nom",num="sg",g="f"),
N("Prämisse","Prämisse","前提","prémisse",c="nom",num="sg",g="f"),
V("wird","werden","〜される","est",p="3sg"),
P("mit","mit","〜で","avec"),
J("bürokratischer","bürokratisch","官僚的な","bureaucratique",c="dat",num="sg",g="f"),
N("Sachlichkeit","Sachlichkeit","冷静さ・客観性","froideur objective",c="dat",num="sg",g="f"),
V("behandelt","behandeln","扱われる","traitée"),
pct(","),
A("was","was","〜ということ","ce qui"),
A("den","der","その","le",c="acc",num="sg",g="m"),
J("typisch","typisch","典型的な","typiquement"),
J("kafkaesken","kafkaesk","カフカ的な","kafkaïen",c="acc",num="sg",g="m"),
N("Stil","Stil","スタイル","style",c="acc",num="sg",g="m"),
V("charakterisiert","charakterisieren","特徴づける","caractérise",p="3sg"),
pct("."),
P("Im","in","〜では","Dans"),
N("Roman","Roman","小説","roman",c="dat",num="sg",g="m"),
pct("„"),
A("Der","der","その","Le",c="nom",num="sg",g="m"),
N("Prozess","Prozess","訴訟・審判","Procès",c="nom",num="sg",g="m"),
pct("""),
V("wird","werden","〜される","est",p="3sg"),
A("der","der","その","le",c="nom",num="sg",g="m"),
N("Protagonist","Protagonist","主人公","protagoniste",c="nom",num="sg",g="m"),
E("Josef K.","ヨーゼフ・K","Josef K."),
V("verhaftet","verhaften","逮捕される","arrêté"),
K("und","und","そして","et"),
P("vor","vor","〜の前に","traduit"),
N("Gericht","Gericht","裁判所","en justice",c="acc",num="sg",g="n"),
V("gestellt","stellen","引き出す",""),
pct(","),
R("ohne","ohne","〜せずに","sans"),
R("je","je","かつて","jamais"),
P("zu","zu","〜することを",""),
V("erfahren","erfahren","知る","savoir"),
pct(","),
J("welches","welcher","どの","quel"),
N("Verbrechen","Verbrechen","犯罪","crime",c="nom",num="sg",g="n"),
Q("ihm","er","彼に","lui"),
V("vorgeworfen","vorwerfen","非難する","est reproché"),
V("wird","werden","〜される","",p="3sg"),
pct("."),
E("Kafka","カフカ","Kafka"),
V("bat","bitten","頼んだ","pria",p="3sg"),
Q("seinen","sein","彼の","son",case="acc",number="sg",gender="m"),
N("Freund","Freund","友人","ami",c="acc",num="sg",g="m"),
E("Max Brod","マックス・ブロート","Max Brod"),
P("vor","vor","〜の前に","avant"),
Q("seinem","sein","彼の","sa",case="dat",number="sg",gender="m"),
N("Tod","Tod","死","mort",c="dat",num="sg",g="m"),
NUM("1924","1924年","1924"),
pct(","),
Q("seine","sein","彼の","ses",case="acc",number="pl"),
N("Manuskripte","Manuskript","原稿","manuscrits",c="acc",num="pl",g="n"),
P("zu","zu","〜するよう","de"),
V("verbrennen","verbrennen","燃やす","brûler"),
pct("."),
N("Brod","Brod","ブロート","Brod",c="nom",num="sg",g="m"),
V("ignorierte","ignorieren","無視した","ignora",p="3sg"),
Q("diesen","dieser","この","ce",case="acc",number="sg",gender="m"),
N("Wunsch","Wunsch","願い","souhait",c="acc",num="sg",g="m"),
K("und","und","そして","et"),
V("veröffentlichte","veröffentlichen","出版した","publia",p="3sg"),
A("die","die","その","les",c="acc",num="pl"),
N("Werke","Werk","作品","œuvres",c="acc",num="pl",g="n"),
pct(","),
A("die","die","〜という","qui"),
E("Kafka","カフカ","Kafka"),
J("weltberühmt","weltberühmt","世界的に有名な","mondialement célèbre"),
V("machten","machen","〜した","rendirent",p="3pl"),
pct("."),
]},

# ════════════════════════════════════════════════════════════
# t104 — Der Klimawandel (~200 Wörter)
# ════════════════════════════════════════════════════════════
{
"id":"t104","title":"Der Klimawandel und seine Folgen",
"subtitle":"Eine globale Herausforderung des 21. Jahrhunderts",
"level":"B2","category":"Wissenschaft",
"tokens":[
A("Der","der","その","le",c="nom",num="sg",g="m"),
N("Klimawandel","Klimawandel","気候変動","changement climatique",c="nom",num="sg",g="m"),
V("ist","sein","〜である","est",p="3sg"),
A("eine","ein","一つの","l'un des",c="nom",num="sg",g="f"),
A("der","der","の","plus grandes",c="gen",num="pl"),
J("größten","groß","最大の","",c="gen",num="pl"),
N("Herausforderungen","Herausforderung","課題","défis",c="gen",num="pl",g="f"),
pct(","),
P("mit","mit","〜で","auxquels"),
A("denen","der","それ",""),
A("die","die","その","l'",c="nom",num="sg",g="f"),
N("Menschheit","Menschheit","人類","humanité",c="nom",num="sg",g="f"),
P("im","in","〜で","au"),
NUM("21.","21","XXIe"),
N("Jahrhundert","Jahrhundert","世紀","siècle",c="dat",num="sg",g="n"),
V("konfrontiert","konfrontieren","直面させられる","est confrontée",p="3sg"),
V("ist","sein","〜である","",p="3sg"),
pct("."),
P("Seit","seit","〜以来","Depuis"),
A("dem","der","その","le début de la",c="dat",num="sg",g="m"),
N("Beginn","Beginn","始まり","",c="dat",num="sg",g="m"),
A("der","der","の","",c="gen",num="sg",g="f"),
N("Industrialisierung","Industrialisierung","工業化","industrialisation",c="gen",num="sg",g="f"),
P("im","in","〜に","au"),
NUM("19.","19","XIXe"),
N("Jahrhundert","Jahrhundert","世紀","siècle",c="dat",num="sg",g="n"),
V("hat","haben","〜した","a",p="3sg"),
A("der","der","その","l'",c="nom",num="sg",g="m"),
N("Mensch","Mensch","人間","être humain",c="nom",num="sg",g="m"),
P("durch","durch","〜によって","par"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Verbrennung","Verbrennung","燃焼","combustion",c="acc",num="sg",g="f"),
J("fossiler","fossil","化石の","de combustibles fossiles",c="gen",num="pl"),
N("Brennstoffe","Brennstoff","燃料","",c="gen",num="pl",g="m"),
J("enorme","enorm","巨大な","d'énormes quantités de",c="acc",num="pl"),
N("Mengen","Menge","量","",c="acc",num="pl",g="f"),
P("an","an","の","de"),
N("Kohlendioxid","Kohlendioxid","二酸化炭素","dioxyde de carbone",c="dat",num="sg",g="n"),
K("und","und","と","et"),
J("anderen","ander","他の","d'autres",c="dat",num="pl"),
N("Treibhausgasen","Treibhausgas","温室効果ガス","gaz à effet de serre",c="dat",num="pl",g="n"),
P("in","in","〜に","dans"),
A("die","die","その","l'",c="acc",num="sg",g="f"),
N("Atmosphäre","Atmosphäre","大気","atmosphère",c="acc",num="sg",g="f"),
V("freigesetzt","freisetzen","放出した","libéré"),
pct("."),
Q("Diese","dieser","これらの","ces",case="nom",number="pl"),
N("Gase","Gas","気体","gaz",c="nom",num="pl",g="n"),
V("wirken","wirken","作用する","agissent",p="3pl"),
P("wie","wie","〜のように","comme"),
A("eine","ein","〜の","une",c="nom",num="sg",g="f"),
N("Glasscheibe","Glasscheibe","ガラス板","vitre",c="nom",num="sg",g="f"),
pct(":"),
Q("Sie","sie","それらは","elles",),
V("lassen","lassen","通す","laissent entrer",p="3pl"),
A("das","das","その","la",c="acc",num="sg",g="n"),
N("Sonnenlicht","Sonnenlicht","太陽光","lumière solaire",c="acc",num="sg",g="n"),
V("herein","herein","中に（lassen）",""),
pct(","),
V("verhindern","verhindern","妨げる","empêchent",p="3pl"),
R("aber","aber","しかし","mais"),
pct(","),
K("dass","dass","〜ということ","que"),
A("die","die","その","la",c="nom",num="sg",g="f"),
N("Wärme","Wärme","熱","chaleur",c="nom",num="sg",g="f"),
A("die","die","その","la",c="acc",num="sg",g="f"),
N("Erde","Erde","地球","Terre",c="acc",num="sg",g="f"),
V("verlässt","verlassen","離れる","quitte",p="3sg"),
pct("."),
A("Die","die","その","les",c="nom",num="pl"),
N("Folgen","Folge","結果","conséquences",c="nom",num="pl",g="f"),
V("sind","sein","〜である","sont",p="3pl"),
R("bereits","bereits","すでに","déjà"),
J("heute","heute","今日","aujourd'hui"),
J("spürbar","spürbar","感じられる","perceptibles"),
pct(":"),
N("Gletscher","Gletscher","氷河","glaciers",c="nom",num="pl",g="m"),
V("schmelzen","schmelzen","溶ける","fondent",p="3pl"),
pct(","),
A("der","der","その","le",c="nom",num="sg",g="m"),
N("Meeresspiegel","Meeresspiegel","海面","niveau de la mer",c="nom",num="sg",g="m"),
V("steigt","steigen","上昇する","monte",p="3sg"),
pct(","),
K("und","und","そして","et"),
J("extreme","extrem","極端な","extrêmes",c="nom",num="pl"),
N("Wetterereignisse","Wetterereignis","気象現象","événements météorologiques",c="nom",num="pl",g="n"),
P("wie","wie","〜のような","tels que"),
N("Hitzewellen","Hitzewelle","熱波","vagues de chaleur",c="nom",num="pl",g="f"),
pct(","),
N("Dürren","Dürre","干ばつ","sécheresses",c="nom",num="pl",g="f"),
K("und","und","と","et"),
N("Überschwemmungen","Überschwemmung","洪水","inondations",c="nom",num="pl",g="f"),
V("nehmen","nehmen","増える","augmentent",p="3pl"),
P("an","an","〜において","en"),
N("Häufigkeit","Häufigkeit","頻度","fréquence",c="dat",num="sg",g="f"),
K("und","und","と","et"),
N("Stärke","Stärke","強さ","intensité",c="dat",num="sg",g="f"),
P("zu","zu","〜へ",""),
pct("."),
P("Um","um","〜するために","pour"),
A("die","die","その","les",c="acc",num="pl"),
J("schlimmsten","schlimm","最悪の","pires",c="acc",num="pl"),
N("Folgen","Folge","結果","conséquences",c="acc",num="pl",g="f"),
A("des","der","の","du",c="gen",num="sg",g="m"),
N("Klimawandels","Klimawandel","気候変動の","changement climatique",c="gen",num="sg",g="m"),
P("abzuwenden","abwenden","回避するために","éviter"),
pct(","),
V("haben","haben","〜した","ont",p="3pl"),
A("die","die","その","les",c="nom",num="pl"),
N("Staaten","Staat","国々","États",c="nom",num="pl",g="m"),
A("der","der","の","du",c="gen",num="sg",g="f"),
N("Welt","Welt","世界","monde",c="gen",num="sg",g="f"),
P("im","in","〜で","dans"),
J("Pariser","pariserisch","パリの","Accord de Paris",c="dat",num="sg",g="n"),
N("Abkommen","Abkommen","協定","",c="dat",num="sg",g="n"),
P("von","von","〜の","de"),
NUM("2015","2015年","2015"),
V("vereinbart","vereinbaren","合意した","convenu"),
pct(","),
A("die","die","その","le",c="acc",num="sg",g="f"),
N("Erderwärmung","Erderwärmung","地球温暖化","réchauffement climatique",c="acc",num="sg",g="f"),
P("auf","auf","〜に","à"),
R("möglichst","möglichst","できるだけ","au maximum"),
NUM("1,5","1.5","1,5"),
N("Grad","Grad","度","degrés",c="acc",num="sg",g="m"),
N("Celsius","Celsius","摂氏","Celsius",c="acc",num="sg",g="m"),
P("über","über","〜を超えて","au-dessus"),
A("dem","der","その","du niveau préindustriel",c="dat",num="sg",g="n"),
J("vorindustriellen","vorindustriell","産業化以前の","",c="dat",num="sg",g="n"),
N("Niveau","Niveau","水準","",c="dat",num="sg",g="n"),
P("zu","zu","〜するよう",""),
V("begrenzen","begrenzen","制限する","limiter"),
pct("."),
Q("Dies","dies","これは","cela"),
V("erfordert","erfordern","必要とする","exige",p="3sg"),
A("eine","ein","〜の","une",c="acc",num="sg",g="f"),
J("drastische","drastisch","大幅な","drastique",c="acc",num="sg",g="f"),
N("Reduzierung","Reduzierung","削減","réduction",c="acc",num="sg",g="f"),
A("der","der","の","des",c="gen",num="pl"),
N("Treibhausgasemissionen","Treibhausgasemission","温室効果ガス排出","émissions de gaz à effet de serre",c="gen",num="pl",g="f"),
P("durch","durch","〜による","grâce à"),
A("den","der","その","la",c="acc",num="sg",g="m"),
N("Übergang","Übergang","移行","transition",c="acc",num="sg",g="m"),
P("zu","zu","〜へ","vers"),
J("erneuerbaren","erneuerbar","再生可能な","renouvelables",c="dat",num="pl"),
N("Energien","Energie","エネルギー","énergies",c="dat",num="pl",g="f"),
K("und","und","と","et"),
J("tiefgreifende","tiefgreifend","根本的な","des changements profonds",c="acc",num="pl"),
N("Veränderungen","Veränderung","変化","",c="acc",num="pl",g="f"),
P("im","in","〜で","dans"),
N("Konsum-","Konsum","消費の","la consommation"),
K("und","und","と","et"),
N("Mobilitätsverhalten","Mobilitätsverhalten","移動行動","comportement de mobilité",c="dat",num="sg",g="n"),
A("der","der","の","de la",c="gen",num="sg",g="f"),
N("Bevölkerung","Bevölkerung","住民・人口","population",c="gen",num="sg",g="f"),
pct("."),
]},

]  # end LONG_TEXTS

def main():
    with open(TEXTS_PATH, encoding='utf-8') as f:
        data = json.load(f)
    existing = {t['id'] for t in data['texts']}
    added = 0
    for t in LONG_TEXTS:
        if t['id'] not in existing:
            data['texts'].append(t)
            added += 1
        else:
            # 上書き更新
            data['texts'] = [t if x['id']==t['id'] else x for x in data['texts']]
            added += 1
    data['meta']['total'] = len(data['texts'])
    with open(TEXTS_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✓ 追加/更新: {added}件 → 合計 {len(data['texts'])}件")

if __name__ == '__main__':
    main()
