#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Ajout de nouveaux textes (histoire, philosophie, chimie, physique, littérature, société)
et de nouveaux mots de vocabulaire.
"""
import json, os

TEXTS_PATH = '/Users/kotai/Documents/Developpement/German/data/texts.json'
VOCAB_PATH = '/Users/kotai/Documents/Developpement/German/data/vocabulary.json'

# ── Helpers ──────────────────────────────────────────────────────────────────

def N(s, l, j, f, c=None, num=None, g=None):
    t = {"surface":s,"pos":"noun","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c:   t["case"]   = c
    if num: t["number"] = num
    if g:   t["gender"] = g
    return t

def A(s, l, j, f, c=None, num=None, g=None):
    t = {"surface":s,"pos":"article","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c:   t["case"]   = c
    if num: t["number"] = num
    if g:   t["gender"] = g
    return t

def V(s, l, j, f, p=None):
    t = {"surface":s,"pos":"verb","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if p: t["person"] = p
    return t

def J(s, l, j, f, c=None, num=None, g=None):
    t = {"surface":s,"pos":"adjective","lemma":l,"meaning_ja":j,"meaning_fr":f}
    if c:   t["case"]   = c
    if num: t["number"] = num
    if g:   t["gender"] = g
    return t

def P(s, l, j, f):
    return {"surface":s,"pos":"preposition","lemma":l,"meaning_ja":j,"meaning_fr":f}

def K(s, l, j, f):
    return {"surface":s,"pos":"conjunction","lemma":l,"meaning_ja":j,"meaning_fr":f}

def R(s, l, j, f):
    return {"surface":s,"pos":"adverb","lemma":l,"meaning_ja":j,"meaning_fr":f}

def Q(s, l, j, f, **kw):
    t = {"surface":s,"pos":"pronoun","lemma":l,"meaning_ja":j,"meaning_fr":f}
    t.update(kw)
    return t

def E(s, j, f):
    return {"surface":s,"pos":"proper_noun","lemma":s,"meaning_ja":j,"meaning_fr":f}

def NUM(s, j, f):
    return {"surface":s,"pos":"number","lemma":s,"meaning_ja":j,"meaning_fr":f}

def pct(s="."):
    return {"surface":s,"pos":"punct"}

# ── Nouveaux textes ───────────────────────────────────────────────────────────

NEUE_TEXTE = [

    # ════════════════════════════════════════════════════════════
    # GESCHICHTE
    # ════════════════════════════════════════════════════════════

    {
        "id": "t080",
        "title": "Die Französische Revolution",
        "subtitle": "Geburt der modernen Demokratie",
        "level": "B2",
        "category": "Geschichte",
        "tokens": [
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            J("Französische","französisch","フランスの","française",c="nom",num="sg",g="f"),
            N("Revolution","Revolution","革命","révolution",c="nom",num="sg",g="f"),
            P("von","von","〜の","de"),
            NUM("1789","1789年","1789"),
            V("veränderte","verändern","根本的に変えた","changea profondément",p="3sg"),
            A("die","die","その","l'",c="acc",num="sg",g="f"),
            J("politische","politisch","政治的な","politique",c="acc",num="sg",g="f"),
            N("Ordnung","Ordnung","秩序・体制","ordre",c="acc",num="sg",g="f"),
            N("Europas","Europa","ヨーロッパの","de l'Europe",c="gen",num="sg",g="n"),
            R("grundlegend","grundlegend","根本的に","fondamentalement"),
            pct("."),
            A("Das","das","その","le",c="nom",num="sg",g="n"),
            N("Volk","Volk","民衆","peuple",c="nom",num="sg",g="n"),
            V("stürzte","stürzen","打倒した","renversa",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Monarchie","Monarchie","君主制","monarchie",c="acc",num="sg",g="f"),
            K("und","und","そして","et"),
            V("proklamierte","proklamieren","宣言した","proclama",p="3sg"),
            A("die","die","その","les",c="acc",num="pl"),
            N("Ideale","Ideal","理想","idéaux",c="acc",num="pl",g="n"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            N("Freiheit","Freiheit","自由","liberté",c="gen",num="sg",g="f"),
            pct(","),
            N("Gleichheit","Gleichheit","平等","égalité",c="gen",num="sg",g="f"),
            K("und","und","と","et"),
            N("Brüderlichkeit","Brüderlichkeit","友愛","fraternité",c="gen",num="sg",g="f"),
            pct("."),
            Q("Diese","dieser","これらの","ces",case="nom",number="pl"),
            N("Ereignisse","Ereignis","出来事","événements",c="nom",num="pl",g="n"),
            V("beeinflussten","beeinflussen","影響を与えた","influencèrent",p="3pl"),
            A("die","die","その","l'",c="acc",num="sg",g="f"),
            N("Entwicklung","Entwicklung","発展","développement",c="acc",num="sg",g="f"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            J("modernen","modern","近代の","moderne",c="gen",num="sg",g="f"),
            N("Demokratie","Demokratie","民主主義","démocratie",c="gen",num="sg",g="f"),
            P("in","in","〜で","dans"),
            J("ganz","ganz","全","toute"),
            N("Europa","Europa","ヨーロッパ","Europe",c="dat",num="sg",g="n"),
            pct("."),
        ]
    },

    {
        "id": "t081",
        "title": "Die Weimarer Republik",
        "subtitle": "Deutschlands erste Demokratie und ihr Scheitern",
        "level": "C1",
        "category": "Geschichte",
        "tokens": [
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            J("Weimarer","weimarisch","ワイマールの","de Weimar",c="nom",num="sg",g="f"),
            N("Republik","Republik","共和国","république",c="nom",num="sg",g="f"),
            pct(","),
            N("Deutschlands","Deutschland","ドイツの","de l'Allemagne",c="gen",num="sg",g="n"),
            J("erste","erst","最初の","première",c="nom",num="sg",g="f"),
            N("Demokratie","Demokratie","民主主義","démocratie",c="nom",num="sg",g="f"),
            pct(","),
            V("existierte","existieren","存在した","exista",p="3sg"),
            P("von","von","〜から","de"),
            NUM("1919","1919年","1919"),
            P("bis","bis","〜まで","jusqu'en"),
            NUM("1933","1933年","1933"),
            pct("."),
            Q("Sie","sie","それは","elle"),
            V("entstand","entstehen","誕生した・成立した","naquit",p="3sg"),
            P("nach","nach","〜の後に","après"),
            A("dem","der","その","la",c="dat",num="sg",g="n"),
            N("Ende","Ende","終わり","fin",c="dat",num="sg",g="n"),
            A("des","der","の","de la",c="gen",num="sg",g="m"),
            J("Ersten","erst","第一の","Première",c="gen",num="sg",g="m"),
            N("Weltkriegs","Weltkrieg","世界大戦の","Guerre mondiale",c="gen",num="sg",g="m"),
            K("und","und","そして","et"),
            V("war","sein","〜であった","était",p="3sg"),
            P("von","von","〜によって","par"),
            J("politischen","politisch","政治的な","politiques",c="dat",num="pl"),
            N("Krisen","Krise","危機（複数）","crises",c="dat",num="pl",g="f"),
            pct(","),
            N("Inflation","Inflation","インフレ","inflation",c="dat",num="sg",g="f"),
            K("und","und","と","et"),
            J("sozialen","sozial","社会的な","sociales",c="dat",num="pl"),
            N("Spannungen","Spannung","緊張・摩擦","tensions",c="dat",num="pl",g="f"),
            V("geprägt","prägen","特徴づけられた","marquée"),
            pct("."),
            Q("Ihr","ihr","その（女性所有格）","son",case="nom",number="sg",gender="n"),
            N("Scheitern","Scheitern","失敗・崩壊","échec",c="nom",num="sg",g="n"),
            V("ebnete","ebnen","道を開いた","ouvrit la voie",p="3sg"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            N("Weg","Weg","道・道筋","chemin",c="acc",num="sg",g="m"),
            P("für","für","のために","pour"),
            A("den","der","その","l'",c="acc",num="sg",g="m"),
            N("Aufstieg","Aufstieg","台頭・興隆","montée",c="acc",num="sg",g="m"),
            A("des","der","の","du",c="gen",num="sg",g="m"),
            N("Nationalsozialismus","Nationalsozialismus","国家社会主義","national-socialisme",c="gen",num="sg",g="m"),
            pct("."),
        ]
    },

    {
        "id": "t082",
        "title": "Das Ende des Zweiten Weltkriegs",
        "subtitle": "Kapitulation und Neuanfang",
        "level": "B2",
        "category": "Geschichte",
        "tokens": [
            P("Am","an","〜に","le"),
            NUM("8.","8日","8"),
            N("Mai","Mai","5月","mai",c="dat",num="sg",g="m"),
            NUM("1945","1945年","1945"),
            V("kapitulierte","kapitulieren","降伏した","capitula",p="3sg"),
            E("Deutschland","ドイツ","l'Allemagne"),
            R("bedingungslos","bedingungslos","無条件に","inconditionnellement"),
            K("und","und","そして","et"),
            V("beendete","beenden","終わらせた","mit fin à",p="3sg"),
            R("damit","damit","それによって","ainsi"),
            A("den","der","その","la",c="acc",num="sg",g="m"),
            J("Zweiten","zweit","第二の","Seconde",c="acc",num="sg",g="m"),
            N("Weltkrieg","Weltkrieg","世界大戦","Guerre mondiale",c="acc",num="sg",g="m"),
            P("in","in","〜で","en"),
            E("Europa","ヨーロッパ","Europe"),
            pct("."),
            A("Der","der","その","la",c="nom",num="sg",g="m"),
            N("Krieg","Krieg","戦争","guerre",c="nom",num="sg",g="m"),
            V("hatte","haben","〜した（過去完了）","avait",p="3sg"),
            N("Millionen","Million","何百万もの","des millions de",c="acc",num="pl",g="f"),
            P("von","von","の","de"),
            N("Menschenleben","Menschenleben","人命","vies humaines",c="dat",num="pl",g="n"),
            V("gefordert","fordern","要求した・奪った","coûté"),
            K("und","und","そして","et"),
            J("weite","weit","広い","de larges",c="acc",num="pl"),
            N("Teile","Teil","部分・地域","parties",c="acc",num="pl",g="m"),
            A("des","der","の","du",c="gen",num="sg",g="m"),
            N("Kontinents","Kontinent","大陸の","continent",c="gen",num="sg",g="m"),
            V("verwüstet","verwüsten","荒廃させた","ravagées"),
            pct("."),
            E("Deutschland","ドイツ","L'Allemagne"),
            V("wurde","werden","〜された（受動）","fut",p="3sg"),
            R("anschließend","anschließend","その後","ensuite"),
            P("in","in","〜に","en"),
            J("vier","vier","四つの","quatre"),
            N("Besatzungszonen","Besatzungszone","占領地域","zones d'occupation",c="acc",num="pl",g="f"),
            V("aufgeteilt","aufteilen","分割された","divisée"),
            pct("."),
        ]
    },

    {
        "id": "t083",
        "title": "Der Fall der Berliner Mauer",
        "subtitle": "Ein historischer Abend im November 1989",
        "level": "B1",
        "category": "Geschichte",
        "tokens": [
            A("Die","die","その","le",c="nom",num="sg",g="f"),
            J("Berliner","berlinerisch","ベルリンの","de Berlin",c="nom",num="sg",g="f"),
            N("Mauer","Mauer","壁","mur",c="nom",num="sg",g="f"),
            V("wurde","werden","〜された","fut",p="3sg"),
            P("am","an","〜に","le"),
            NUM("9.","9日","9"),
            N("November","November","11月","novembre",c="dat",num="sg",g="m"),
            NUM("1989","1989年","1989"),
            V("geöffnet","öffnen","開かれた","ouvert"),
            pct("."),
            N("Tausende","Tausend","何千もの人々","des milliers",c="nom",num="pl",g="m"),
            P("von","von","の","de"),
            N("Menschen","Mensch","人々","personnes",c="dat",num="pl",g="m"),
            V("strömten","strömen","押し寄せた・流れた","affluèrent",p="3pl"),
            P("durch","durch","〜を通って","par"),
            A("die","die","その","les",c="acc",num="pl"),
            N("Grenzübergänge","Grenzübergang","国境検問所","postes-frontières",c="acc",num="pl",g="m"),
            P("von","von","〜から","de"),
            E("Ost-","東ベルリンから","Berlin-Est"),
            P("nach","nach","〜へ","vers"),
            E("Westberlin","西ベルリン","Berlin-Ouest"),
            pct("."),
            Q("Dieser","dieser","この","cet",case="nom",number="sg",gender="m"),
            J("historische","historisch","歴史的な","historique",c="nom",num="sg",g="m"),
            N("Moment","Moment","瞬間・出来事","moment",c="nom",num="sg",g="m"),
            V("markierte","markieren","示した・画した","marqua",p="3sg"),
            A("das","das","その","la",c="acc",num="sg",g="n"),
            N("Ende","Ende","終わり","fin",c="acc",num="sg",g="n"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            J("deutschen","deutsch","ドイツの","allemande",c="gen",num="sg",g="f"),
            N("Teilung","Teilung","分断","division",c="gen",num="sg",g="f"),
            K("und","und","そして","et"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            N("Beginn","Beginn","始まり","début",c="acc",num="sg",g="m"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            N("Wiedervereinigung","Wiedervereinigung","再統一","réunification",c="gen",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t084",
        "title": "Das Zeitalter der Aufklärung",
        "subtitle": "Vernunft als höchster Wert",
        "level": "C1",
        "category": "Geschichte",
        "tokens": [
            A("Das","das","その","le",c="nom",num="sg",g="n"),
            N("Zeitalter","Zeitalter","時代","ère",c="nom",num="sg",g="n"),
            A("der","der","の","de l'",c="gen",num="sg",g="f"),
            N("Aufklärung","Aufklärung","啓蒙主義","Lumières",c="gen",num="sg",g="f"),
            P("im","in","〜世紀に","au",),
            NUM("17.","17","XVII"),
            K("und","und","と","et"),
            NUM("18.","18","XVIII"),
            N("Jahrhundert","Jahrhundert","世紀","siècle",c="dat",num="sg",g="n"),
            V("stellte","stellen","置いた・据えた","plaça",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Vernunft","Vernunft","理性","raison",c="acc",num="sg",g="f"),
            P("in","in","〜の","au"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            N("Mittelpunkt","Mittelpunkt","中心","centre",c="acc",num="sg",g="m"),
            A("des","der","の","de la",c="gen",num="sg",g="n"),
            J("menschlichen","menschlich","人間の","humaine",c="gen",num="sg",g="n"),
            N("Denkens","Denken","思考・思索の","pensée",c="gen",num="sg",g="n"),
            pct("."),
            N("Philosophen","Philosoph","哲学者たち","philosophes",c="nom",num="pl",g="m"),
            P("wie","wie","〜のような","comme"),
            E("Voltaire","ヴォルテール","Voltaire"),
            pct(","),
            E("Rousseau","ルソー","Rousseau"),
            K("und","und","と","et"),
            E("Kant","カント","Kant"),
            V("forderten","fordern","要求した","réclamèrent",p="3pl"),
            A("die","die","その","le",c="acc",num="sg",g="f"),
            J("kritische","kritisch","批判的な","critique",c="acc",num="sg",g="f"),
            N("Überprüfung","Überprüfung","再検討・批判","remise en question",c="acc",num="sg",g="f"),
            J("aller","aller","すべての","toutes les",c="gen",num="pl"),
            N("Autoritäten","Autorität","権威","autorités",c="gen",num="pl",g="f"),
            pct("."),
            Q("Diese","dieser","この","ce",case="nom",number="sg",gender="f"),
            J("intellektuelle","intellektuell","知的な","intellectuelle",c="nom",num="sg",g="f"),
            N("Bewegung","Bewegung","運動","mouvement",c="nom",num="sg",g="f"),
            V("legte","legen","築いた","posa",p="3sg"),
            A("die","die","その","les",c="acc",num="pl"),
            J("ideellen","ideell","思想的な","idéologiques",c="acc",num="pl"),
            N("Grundlagen","Grundlage","基礎","bases",c="acc",num="pl",g="f"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            J("modernen","modern","近代の","moderne",c="gen",num="sg",g="f"),
            N("Demokratie","Demokratie","民主主義","démocratie",c="gen",num="sg",g="f"),
            K("und","und","と","et"),
            A("der","der","の","des",c="gen",num="pl"),
            N("Menschenrechte","Menschenrecht","人権","droits de l'homme",c="gen",num="pl",g="n"),
            pct("."),
        ]
    },

    # ════════════════════════════════════════════════════════════
    # PHILOSOPHIE
    # ════════════════════════════════════════════════════════════

    {
        "id": "t085",
        "title": "Kants kategorischer Imperativ",
        "subtitle": "Das Grundprinzip der Vernunftethik",
        "level": "C1",
        "category": "Philosophie",
        "tokens": [
            E("Immanuel Kant","イマヌエル・カント","Immanuel Kant"),
            V("entwickelte","entwickeln","発展させた・提唱した","élabora",p="3sg"),
            A("den","der","その","l'",c="acc",num="sg",g="m"),
            J("kategorischen","kategorisch","定言的な","catégorique",c="acc",num="sg",g="m"),
            N("Imperativ","Imperativ","命令法・命令","impératif",c="acc",num="sg",g="m"),
            P("als","als","〜として","comme"),
            J("zentrales","zentral","中心的な","principe central",c="acc",num="sg",g="n"),
            N("Prinzip","Prinzip","原理","principe",c="acc",num="sg",g="n"),
            Q("seiner","sein","彼の","de sa",case="gen",number="sg",gender="f"),
            N("Ethik","Ethik","倫理学","éthique",c="gen",num="sg",g="f"),
            pct("."),
            Q("Dieser","dieser","この","cet",case="nom",number="sg",gender="m"),
            N("Grundsatz","Grundsatz","基本原則","principe fondamental",c="nom",num="sg",g="m"),
            V("lautet","lauten","述べる・〜という","stipule",p="3sg"),
            pct(":"),
            V("Handle","handeln","行為せよ","agis",p="2sg"),
            R("nur","nur","のみ・ただ","seulement"),
            P("nach","nach","〜に従って","selon"),
            Q("derjenigen","derjenige","その","la",case="dat",number="sg",gender="f"),
            N("Maxime","Maxime","格率・行動原則","maxime",c="dat",num="sg",g="f"),
            pct(","),
            P("durch","durch","〜によって","par laquelle"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            Q("du","du","あなたは","tu"),
            R("zugleich","zugleich","同時に","en même temps"),
            V("wollen","wollen","望む","puisses vouloir"),
            V("kannst","können","できる",""),
            pct(","),
            K("dass","dass","〜ということ","qu'"),
            Q("sie","sie","それが","elle"),
            A("ein","ein","一つの","une",c="nom",num="sg",g="n"),
            J("allgemeines","allgemein","普遍的な","universelle",c="nom",num="sg",g="n"),
            N("Gesetz","Gesetz","法則・法","loi",c="nom",num="sg",g="n"),
            V("werde","werden","なる","devienne"),
            pct("."),
            E("Kant","カント","Kant"),
            V("forderte","fordern","要求した","exigeait",p="3sg"),
            R("damit","damit","それによって","ainsi"),
            pct(","),
            K("dass","dass","〜ということ","que"),
            J("moralisches","moralisch","道徳的な","l'action morale",c="nom",num="sg",g="n"),
            N("Handeln","Handeln","行為・行動","action",c="nom",num="sg",g="n"),
            R("universell","universell","普遍的に","universellement"),
            K("und","und","そして","et"),
            J("vernunftgeleitet","vernunftgeleitet","理性に基づく","guidée par la raison"),
            V("sein","sein","〜である","soit"),
            V("muss","müssen","〜でなければならない",""),
            pct("."),
        ]
    },

    {
        "id": "t086",
        "title": "Nietzsche und der Wille zur Macht",
        "subtitle": "Jenseits von Gut und Böse",
        "level": "C1",
        "category": "Philosophie",
        "tokens": [
            E("Friedrich Nietzsche","フリードリヒ・ニーチェ","Friedrich Nietzsche"),
            V("prägte","prägen","生み出した・刻んだ","forgea",p="3sg"),
            A("den","der","その","la",c="acc",num="sg",g="m"),
            N("Begriff","Begriff","概念","concept",c="acc",num="sg",g="m"),
            A("des","der","の","de la",c="gen",num="sg",g="m"),
            N("Willens","Wille","意志の","volonté",c="gen",num="sg",g="m"),
            P("zur","zu","〜への","de",),
            N("Macht","Macht","権力・力","puissance",c="dat",num="sg",g="f"),
            P("als","als","〜として","comme"),
            J("zentrale","zentral","中心的な","force centrale",c="acc",num="sg",g="f"),
            N("Triebkraft","Triebkraft","駆動力","force motrice",c="acc",num="sg",g="f"),
            A("des","der","の","de la",c="gen",num="sg",g="n"),
            J("menschlichen","menschlich","人間の","humaine",c="gen",num="sg",g="n"),
            N("Lebens","Leben","生の","vie",c="gen",num="sg",g="n"),
            pct("."),
            Q("Er","er","彼は","il"),
            V("kritisierte","kritisieren","批判した","critiqa",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            J("christliche","christlich","キリスト教的な","chrétienne",c="acc",num="sg",g="f"),
            N("Moral","Moral","道徳","morale",c="acc",num="sg",g="f"),
            P("als","als","〜として","comme"),
            N("Sklavenmoral","Sklavenmoral","奴隷道徳","morale des esclaves",c="acc",num="sg",g="f"),
            K("und","und","そして","et"),
            V("forderte","fordern","要求した","appela",p="3sg"),
            Q("ihre","ihr","その","son",case="acc",number="sg",gender="f"),
            N("Überwindung","Überwindung","克服","dépassement",c="acc",num="sg",g="f"),
            P("durch","durch","〜によって","par"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            N("Übermenschen","Übermensch","超人","surhomme",c="acc",num="sg",g="m"),
            pct("."),
            Q("Sein","sein","彼の","son",case="nom",number="sg",gender="n"),
            N("Werk","Werk","著作・作品","œuvre",c="nom",num="sg",g="n"),
            V("beeinflusste","beeinflussen","影響を与えた","influença",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Philosophie","Philosophie","哲学","philosophie",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Literatur","Literatur","文学","littérature",c="acc",num="sg",g="f"),
            A("des","der","の","du",c="gen",num="sg",g="n"),
            NUM("20.","20","XX"),
            N("Jahrhunderts","Jahrhundert","世紀の","siècle",c="gen",num="sg",g="n"),
            R("nachhaltig","nachhaltig","持続的に・深く","durablement"),
            pct("."),
        ]
    },

    {
        "id": "t087",
        "title": "Platons Ideenlehre",
        "subtitle": "Die wahre Wirklichkeit hinter den Erscheinungen",
        "level": "B2",
        "category": "Philosophie",
        "tokens": [
            E("Platon","プラトン","Platon"),
            V("lehrte","lehren","教えた","enseigna",p="3sg"),
            pct(","),
            K("dass","dass","〜ということ","que"),
            P("hinter","hinter","〜の背後に","derrière"),
            A("der","der","その","le",c="dat",num="sg",g="f"),
            J("sichtbaren","sichtbar","見える","visible",c="dat",num="sg",g="f"),
            N("Welt","Welt","世界","monde",c="dat",num="sg",g="f"),
            A("eine","ein","一つの","un",c="nom",num="sg",g="f"),
            J("unvergängliche","unvergänglich","不滅の","éternel",c="nom",num="sg",g="f"),
            N("Welt","Welt","世界","monde",c="nom",num="sg",g="f"),
            A("der","der","の","des",c="gen",num="pl"),
            N("Ideen","Idee","イデアの","idées",c="gen",num="pl",g="f"),
            V("existiert","existieren","存在する","existe",p="3sg"),
            pct("."),
            P("Im","in","〜の中で","Dans le",),
            N("Höhlengleichnis","Höhlengleichnis","洞窟の比喩","mythe de la caverne",c="dat",num="sg",g="n"),
            V("veranschaulichte","veranschaulichen","示した・例示した","illustra",p="3sg"),
            Q("er","er","彼は","il"),
            pct(","),
            K("wie","wie","いかに〜か","comment"),
            N("Menschen","Mensch","人間","hommes",c="nom",num="pl",g="m"),
            R("nur","nur","ただ","seulement"),
            N("Schatten","Schatten","影","ombres",c="acc",num="pl",g="m"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            J("wahren","wahr","真の","vraie",c="gen",num="sg",g="f"),
            N("Wirklichkeit","Wirklichkeit","現実","réalité",c="gen",num="sg",g="f"),
            V("wahrnehmen","wahrnehmen","知覚する","perçoivent",p="3pl"),
            pct("."),
            P("Für","für","〜にとって","Pour"),
            E("Platon","プラトン","Platon"),
            V("besteht","bestehen","ある・からなる","consiste",p="3sg"),
            J("wahre","wahr","真の","vraie",c="nom",num="sg",g="f"),
            N("Erkenntnis","Erkenntnis","認識・知識","connaissance",c="nom",num="sg",g="f"),
            P("im","in","〜の中に","dans l'"),
            N("Aufstieg","Aufstieg","上昇","ascension",c="dat",num="sg",g="m"),
            P("von","von","〜から","de la"),
            A("der","der","その","la",c="dat",num="sg",g="f"),
            J("sinnlichen","sinnlich","感覚的な","sensible",c="dat",num="sg",g="f"),
            N("Erscheinung","Erscheinung","現象・外観","apparence",c="dat",num="sg",g="f"),
            P("zur","zu","〜へ","vers l'",),
            J("ewigen","ewig","永遠の","éternelle",c="dat",num="sg",g="f"),
            N("Idee","Idee","イデア・理念","idée",c="dat",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t088",
        "title": "Der Existentialismus",
        "subtitle": "Die Existenz geht der Essenz voraus",
        "level": "C1",
        "category": "Philosophie",
        "tokens": [
            A("Der","der","その","le",c="nom",num="sg",g="m"),
            N("Existentialismus","Existentialismus","実存主義","existentialisme",c="nom",num="sg",g="m"),
            pct(","),
            V("vertreten","vertreten","代表される","représenté"),
            P("durch","durch","〜によって","par"),
            E("Sartre","サルトル","Sartre"),
            K("und","und","と","et"),
            E("Camus","カミュ","Camus"),
            pct(","),
            V("betont","betonen","強調する","souligne",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            J("radikale","radikal","根本的な","radicale",c="acc",num="sg",g="f"),
            N("Freiheit","Freiheit","自由","liberté",c="acc",num="sg",g="f"),
            A("des","der","の","de l'",c="gen",num="sg",g="m"),
            J("einzelnen","einzeln","個々の","individuel",c="gen",num="sg",g="m"),
            N("Menschen","Mensch","人間の","homme",c="gen",num="sg",g="m"),
            pct("."),
            E("Sartres","サルトルの","de Sartre"),
            N("These","These","テーゼ・命題","thèse",c="nom",num="sg",g="f"),
            pct("„"),
            A("Die","die","その","l'",c="nom",num="sg",g="f"),
            N("Existenz","Existenz","実存","existence",c="nom",num="sg",g="f"),
            V("geht","gehen","先行する・を超える","précède",p="3sg"),
            A("der","der","の","à l'",c="dat",num="sg",g="f"),
            N("Essenz","Essenz","本質","essence",c="dat",num="sg",g="f"),
            R("voraus","voraus","前に",""),
            pct(chr(8222)),
            V("bedeutet","bedeuten","意味する","signifie",p="3sg"),
            pct(","),
            K("dass","dass","〜ということ","que"),
            A("der","der","その","l'",c="nom",num="sg",g="m"),
            N("Mensch","Mensch","人間","homme",c="nom",num="sg",g="m"),
            Q("sich","sich","自分自身を","se"),
            P("durch","durch","〜によって","par"),
            Q("seine","sein","自分の","ses",case="acc",number="pl"),
            N("Entscheidungen","Entscheidung","決断","décisions",c="acc",num="pl",g="f"),
            R("selbst","selbst","自ら","lui-même"),
            V("definiert","definieren","定義する","définit",p="3sg"),
            pct("."),
            Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
            N("Philosophie","Philosophie","哲学","philosophie",c="nom",num="sg",g="f"),
            V("entstand","entstehen","生まれた","naquit",p="3sg"),
            P("als","als","〜として","comme"),
            N("Antwort","Antwort","応答・答え","réponse",c="nom",num="sg",g="f"),
            P("auf","auf","〜に対する","à"),
            A("die","die","その","le",c="acc",num="sg",g="f"),
            J("existentielle","existentiell","実存的な","existentiel",c="acc",num="sg",g="f"),
            N("Sinnlosigkeit","Sinnlosigkeit","無意味・虚無感","absurdité",c="acc",num="sg",g="f"),
            P("nach","nach","〜の後の","après"),
            A("dem","der","その","la",c="dat",num="sg",g="m"),
            J("Zweiten","zweit","第二の","Seconde",c="dat",num="sg",g="m"),
            N("Weltkrieg","Weltkrieg","世界大戦","Guerre mondiale",c="dat",num="sg",g="m"),
            pct("."),
        ]
    },

    # ════════════════════════════════════════════════════════════
    # CHEMIE / NATURWISSENSCHAFTEN
    # ════════════════════════════════════════════════════════════

    {
        "id": "t089",
        "title": "Das Atom und seine Struktur",
        "subtitle": "Grundbausteine der Materie",
        "level": "B2",
        "category": "Wissenschaft",
        "tokens": [
            A("Das","das","その","l'",c="nom",num="sg",g="n"),
            N("Atom","Atom","原子","atome",c="nom",num="sg",g="n"),
            V("besteht","bestehen","からなる","est composé",p="3sg"),
            P("aus","aus","〜から","d'"),
            A("einem","ein","一つの","un",c="dat",num="sg",g="m"),
            N("Kern","Kern","核","noyau",c="dat",num="sg",g="m"),
            P("mit","mit","〜を持つ","contenant des"),
            N("Protonen","Proton","陽子（複数）","protons",c="dat",num="pl",g="n"),
            K("und","und","と","et"),
            N("Neutronen","Neutron","中性子（複数）","neutrons",c="dat",num="pl",g="n"),
            R("sowie","sowie","また〜も","ainsi que"),
            A("einer","ein","一つの","une",c="dat",num="sg",g="f"),
            N("Elektronenhülle","Elektronenhülle","電子殻","couche électronique",c="dat",num="sg",g="f"),
            pct("."),
            A("Die","die","その","le",c="nom",num="sg",g="f"),
            N("Ordnungszahl","Ordnungszahl","原子番号","numéro atomique",c="nom",num="sg",g="f"),
            A("eines","ein","一つの","d'un",c="gen",num="sg",g="n"),
            N("Elements","Element","元素の","élément",c="gen",num="sg",g="n"),
            V("entspricht","entsprechen","相当する","correspond",p="3sg"),
            A("der","der","その","au",c="dat",num="sg",g="f"),
            N("Anzahl","Anzahl","数","nombre",c="dat",num="sg",g="f"),
            A("der","der","の","de",c="gen",num="pl"),
            N("Protonen","Proton","陽子の","protons",c="gen",num="pl",g="n"),
            P("im","in","〜の中の","dans le"),
            N("Kern","Kern","核","noyau",c="dat",num="sg",g="m"),
            K("und","und","そして","et"),
            V("bestimmt","bestimmen","決定する","détermine",p="3sg"),
            Q("seine","sein","その","ses",case="acc",number="pl"),
            J("chemischen","chemisch","化学的な","chimiques",c="acc",num="pl"),
            N("Eigenschaften","Eigenschaft","性質","propriétés",c="acc",num="pl",g="f"),
            pct("."),
            P("Durch","durch","〜によって","Par"),
            A("die","die","その","l'",c="acc",num="sg",g="f"),
            N("Aufnahme","Aufnahme","取り込み","capture",c="acc",num="sg",g="f"),
            K("oder","oder","または","ou"),
            N("Abgabe","Abgabe","放出","libération",c="acc",num="sg",g="f"),
            P("von","von","の","de"),
            N("Elektronen","Elektron","電子","électrons",c="dat",num="pl",g="n"),
            V("entstehen","entstehen","生じる","se forment",p="3pl"),
            N("Ionen","Ion","イオン","ions",c="nom",num="pl",g="n"),
            P("mit","mit","〜を持つ","avec une charge"),
            J("positiver","positiv","正の","positive",c="dat",num="sg",g="f"),
            K("oder","oder","または","ou"),
            J("negativer","negativ","負の","négative",c="dat",num="sg",g="f"),
            N("Ladung","Ladung","電荷","charge",c="dat",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t090",
        "title": "Das Periodensystem der Elemente",
        "subtitle": "Ordnung in der Welt der Chemie",
        "level": "B1",
        "category": "Wissenschaft",
        "tokens": [
            A("Das","das","その","le",c="nom",num="sg",g="n"),
            N("Periodensystem","Periodensystem","周期表","tableau périodique",c="nom",num="sg",g="n"),
            A("der","der","の","des",c="gen",num="pl"),
            N("Elemente","Element","元素の","éléments",c="gen",num="pl",g="n"),
            V("ordnet","ordnen","分類する","classe",p="3sg"),
            J("alle","aller","すべての","tous les",c="acc",num="pl"),
            J("bekannten","bekannt","知られている","connus",c="acc",num="pl"),
            J("chemischen","chemisch","化学的な","chimiques",c="acc",num="pl"),
            N("Elemente","Element","元素","éléments",c="acc",num="pl",g="n"),
            P("nach","nach","〜によって","selon"),
            Q("ihrer","ihr","それらの","leur",case="dat",number="sg",gender="f"),
            N("Ordnungszahl","Ordnungszahl","原子番号","numéro atomique",c="dat",num="sg",g="f"),
            pct("."),
            N("Elemente","Element","元素","éléments",c="nom",num="pl",g="n"),
            P("in","in","〜の中の","dans le"),
            A("der","der","その","le",c="dat",num="sg",g="f"),
            J("gleichen","gleich","同じ","même",c="dat",num="sg",g="f"),
            N("Gruppe","Gruppe","グループ","groupe",c="dat",num="sg",g="f"),
            V("weisen","weisen","示す","présentent",p="3pl"),
            J("ähnliche","ähnlich","類似した","similaires",c="acc",num="pl"),
            J("chemische","chemisch","化学的な","chimiques",c="acc",num="pl"),
            N("Eigenschaften","Eigenschaft","性質","propriétés",c="acc",num="pl",g="f"),
            R("auf","auf","〜を（aufweisen）",""),
            pct(","),
            K("da","da","なぜなら〜だから","car"),
            Q("sie","sie","それらは","ils"),
            A("die","die","その","le même",c="acc",num="sg",g="f"),
            J("gleiche","gleich","同じ",""),
            N("Anzahl","Anzahl","数","nombre",c="acc",num="sg",g="f"),
            P("von","von","の","de"),
            N("Valenzelektronen","Valenzelektron","価電子","électrons de valence",c="dat",num="pl",g="n"),
            V("besitzen","besitzen","持っている","possèdent",p="3pl"),
            pct("."),
            A("Das","das","その","le",c="nom",num="sg",g="n"),
            N("System","System","システム","système",c="nom",num="sg",g="n"),
            V("wurde","werden","〜された","fut",p="3sg"),
            P("im","in","〜に","en"),
            N("Jahr","Jahr","年","an",c="dat",num="sg",g="n"),
            NUM("1869","1869年","1869"),
            P("von","von","によって","par"),
            E("Dmitri Mendelejew","ドミトリ・メンデレーエフ","Dmitri Mendeleïev"),
            V("erstellt","erstellen","作成した","créé"),
            K("und","und","そして","et"),
            V("umfasst","umfassen","含む","comprend",p="3sg"),
            R("heute","heute","今日","aujourd'hui"),
            NUM("118","118個の","118"),
            N("Elemente","Element","元素","éléments",c="acc",num="pl",g="n"),
            pct("."),
        ]
    },

    {
        "id": "t091",
        "title": "Chemische Reaktionen und Energie",
        "subtitle": "Exotherme und endotherme Prozesse",
        "level": "B2",
        "category": "Wissenschaft",
        "tokens": [
            P("Bei","bei","〜において","Lors de"),
            J("chemischen","chemisch","化学的な","chimiques",c="dat",num="pl"),
            N("Reaktionen","Reaktion","反応","réactions",c="dat",num="pl",g="f"),
            V("werden","werden","〜される","sont"),
            J("bestehende","bestehend","既存の","existantes",c="nom",num="pl"),
            N("Bindungen","Bindung","結合","liaisons",c="nom",num="pl",g="f"),
            V("gebrochen","brechen","切断された","rompues"),
            K("und","und","そして","et"),
            J("neue","neu","新しい","de nouvelles",c="nom",num="pl"),
            V("gebildet","bilden","形成された","formées"),
            pct("."),
            J("Exotherme","exotherm","発熱の","exothermiques",c="nom",num="pl"),
            N("Reaktionen","Reaktion","反応","réactions",c="nom",num="pl",g="f"),
            V("geben","geben","放出する","libèrent",p="3pl"),
            N("Energie","Energie","エネルギー","énergie",c="acc",num="sg",g="f"),
            P("in","in","〜の形で","sous forme de"),
            N("Form","Form","形・形態","",c="dat",num="sg",g="f"),
            P("von","von","の","de"),
            N("Wärme","Wärme","熱","chaleur",c="dat",num="sg",g="f"),
            K("oder","oder","または","ou de"),
            N("Licht","Licht","光","lumière",c="dat",num="sg",g="n"),
            R("ab","ab","〜（ausgeben）",""),
            pct(","),
            J("endotherme","endotherm","吸熱の","endothermiques",c="nom",num="pl"),
            R("dagegen","dagegen","それに対して","tandis que les endothermiques"),
            V("nehmen","nehmen","受け取る","absorbent",p="3pl"),
            N("Energie","Energie","エネルギー","énergie",c="acc",num="sg",g="f"),
            R("auf","auf","〜（aufnehmen）",""),
            pct("."),
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            N("Verbrennung","Verbrennung","燃焼","combustion",c="nom",num="sg",g="f"),
            pct(","),
            R("also","also","つまり・すなわち","c'est-à-dire"),
            A("die","die","その","l'",c="nom",num="sg",g="f"),
            N("Oxidation","Oxidation","酸化","oxydation",c="nom",num="sg",g="f"),
            J("kohlenstoffhaltiger","kohlenstoffhaltig","炭素を含む","de composés carbonés",c="gen",num="pl"),
            N("Verbindungen","Verbindung","化合物","composés",c="gen",num="pl",g="f"),
            pct(","),
            V("ist","sein","〜である","est",p="3sg"),
            A("eine","ein","一つの","l'une des",c="nom",num="sg",g="f"),
            A("der","der","の","plus",c="gen",num="pl"),
            J("häufigsten","häufig","最も多い","fréquentes",c="gen",num="pl"),
            J("exothermen","exotherm","発熱の","exothermiques",c="gen",num="pl"),
            N("Reaktionen","Reaktion","反応","réactions",c="gen",num="pl",g="f"),
            P("in","in","〜で","dans"),
            A("der","der","その","la",c="dat",num="sg",g="f"),
            N("Natur","Natur","自然","nature",c="dat",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t092",
        "title": "Einsteins Relativitätstheorie",
        "subtitle": "Raum, Zeit und die Äquivalenz von Masse und Energie",
        "level": "C1",
        "category": "Wissenschaft",
        "tokens": [
            E("Einsteins","アインシュタインの","d'Einstein"),
            J("spezielle","speziell","特殊な","spéciale",c="nom",num="sg",g="f"),
            N("Relativitätstheorie","Relativitätstheorie","相対性理論","théorie de la relativité",c="nom",num="sg",g="f"),
            P("von","von","〜の","de"),
            NUM("1905","1905年","1905"),
            V("zeigte","zeigen","示した","montra",p="3sg"),
            pct(","),
            K("dass","dass","〜ということ","que"),
            N("Raum","Raum","空間","l'espace",c="nom",num="sg",g="m"),
            K("und","und","と","et"),
            N("Zeit","Zeit","時間","le temps",c="nom",num="sg",g="f"),
            J("keine","kein","〜ではない","ne sont pas des",c="nom",num="pl"),
            J("absoluten","absolut","絶対的な","absolues",c="nom",num="pl"),
            N("Größen","Größe","量・値","grandeurs",c="nom",num="pl",g="f"),
            V("sind","sein","〜である","",p="3pl"),
            pct(","),
            K("sondern","sondern","しかし〜である","mais dépendent"),
            P("vom","von","〜によって","de l'"),
            N("Bewegungszustand","Bewegungszustand","運動状態","état de mouvement",c="dat",num="sg",g="m"),
            A("des","der","の","de l'",c="gen",num="sg",g="m"),
            N("Beobachters","Beobachter","観察者の","observateur",c="gen",num="sg",g="m"),
            V("abhängen","abhängen","依存する",""),
            pct("."),
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            N("Formel","Formel","式・公式","formule",c="nom",num="sg",g="f"),
            N("E=mc²","E=mc²","E=mc²","E=mc²"),
            V("besagt","besagen","述べる・意味する","stipule",p="3sg"),
            pct(","),
            K("dass","dass","〜ということ","que"),
            N("Masse","Masse","質量","masse",c="nom",num="sg",g="f"),
            P("in","in","〜に","en"),
            N("Energie","Energie","エネルギー","énergie",c="acc",num="sg",g="f"),
            V("umgewandelt","umwandeln","変換された","peut être convertie"),
            V("werden","werden","〜される",""),
            V("kann","können","できる","",p="3sg"),
            K("und","und","そして","et"),
            R("umgekehrt","umgekehrt","逆に","vice versa"),
            pct("."),
            Q("Diese","dieser","この","cette",case="nom",number="sg",gender="f"),
            N("Erkenntnis","Erkenntnis","認識・発見","découverte",c="nom",num="sg",g="f"),
            V("legte","legen","築いた","posa",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            J("theoretische","theoretisch","理論的な","théorique",c="acc",num="sg",g="f"),
            N("Grundlage","Grundlage","基礎","base",c="acc",num="sg",g="f"),
            P("für","für","のための","pour"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Kernspaltung","Kernspaltung","核分裂","fission nucléaire",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Nutzung","Nutzung","利用","utilisation",c="acc",num="sg",g="f"),
            A("der","der","の","de l'",c="gen",num="sg",g="f"),
            N("Kernenergie","Kernenergie","核エネルギー","énergie nucléaire",c="gen",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t093",
        "title": "Die Fotosynthese",
        "subtitle": "Wie Pflanzen Licht in Leben verwandeln",
        "level": "B2",
        "category": "Wissenschaft",
        "tokens": [
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            N("Fotosynthese","Fotosynthese","光合成","photosynthèse",c="nom",num="sg",g="f"),
            V("ist","sein","〜である","est",p="3sg"),
            A("der","der","その","le",c="nom",num="sg",g="m"),
            N("Prozess","Prozess","過程・プロセス","processus",c="nom",num="sg",g="m"),
            pct(","),
            P("durch","durch","〜によって","par lequel"),
            A("den","der","その","",c="acc",num="sg",g="m"),
            N("Pflanzen","Pflanze","植物","plantes",c="nom",num="pl",g="f"),
            K("und","und","と","et"),
            N("Algen","Alge","藻類","algues",c="nom",num="pl",g="f"),
            N("Lichtenergie","Lichtenergie","光エネルギー","énergie lumineuse",c="acc",num="sg",g="f"),
            P("in","in","〜に","en"),
            J("chemische","chemisch","化学的な","chimique",c="acc",num="sg",g="f"),
            N("Energie","Energie","エネルギー","énergie",c="acc",num="sg",g="f"),
            V("umwandeln","umwandeln","変換する","convertissent",p="3pl"),
            pct("."),
            P("Mithilfe","mithilfe","〜の助けで","Grâce au"),
            A("des","der","の","du",c="gen",num="sg",g="n"),
            N("Chlorophylls","Chlorophyll","葉緑素の","chlorophylle",c="gen",num="sg",g="n"),
            V("werden","werden","〜される","sont"),
            N("Kohlendioxid","Kohlendioxid","二酸化炭素","dioxyde de carbone",c="nom",num="sg",g="n"),
            K("und","und","と","et"),
            N("Wasser","Wasser","水","eau",c="nom",num="sg",g="n"),
            P("in","in","〜に","en"),
            N("Glucose","Glucose","グルコース","glucose",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            N("Sauerstoff","Sauerstoff","酸素","oxygène",c="acc",num="sg",g="m"),
            V("umgewandelt","umwandeln","変換された","convertis"),
            pct("."),
            Q("Dieser","dieser","この","ce",case="nom",number="sg",gender="m"),
            J("biochemische","biochemisch","生化学的な","biochimique",c="nom",num="sg",g="m"),
            N("Vorgang","Vorgang","過程","processus",c="nom",num="sg",g="m"),
            V("ist","sein","〜である","est",p="3sg"),
            A("die","die","その","la",c="nom",num="sg",g="f"),
            N("Basis","Basis","基礎","base",c="nom",num="sg",g="f"),
            A("des","der","の","de la quasi-totalité de la",c="gen",num="sg",g="n"),
            J("gesamten","gesamt","全体の","",c="gen",num="sg",g="n"),
            N("Lebens","Leben","生命の","vie",c="gen",num="sg",g="n"),
            P("auf","auf","〜上の","sur"),
            A("der","der","その","la",c="dat",num="sg",g="f"),
            N("Erde","Erde","地球","Terre",c="dat",num="sg",g="f"),
            K("und","und","そして","et"),
            V("reguliert","regulieren","調節する","régule",p="3sg"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            J("globalen","global","地球規模の","mondial",c="acc",num="sg",g="m"),
            N("Kohlenstoffkreislauf","Kohlenstoffkreislauf","炭素循環","cycle du carbone",c="acc",num="sg",g="m"),
            pct("."),
        ]
    },

    # ════════════════════════════════════════════════════════════
    # LITERATUR
    # ════════════════════════════════════════════════════════════

    {
        "id": "t094",
        "title": "Goethes Faust",
        "subtitle": "Der Gelehrte und der Teufelspakt",
        "level": "B2",
        "category": "Literatur",
        "tokens": [
            E("Goethes","ゲーテの","de Goethe"),
            N("Faust","Faust","ファウスト","Faust",c="nom",num="sg",g="m"),
            V("gilt","gelten","見なされる","est considéré",p="3sg"),
            P("als","als","〜として","comme"),
            A("das","das","その","le",c="nom",num="sg",g="n"),
            J("bedeutendste","bedeutend","最も重要な","plus important",c="nom",num="sg",g="n"),
            N("Werk","Werk","作品","œuvre",c="nom",num="sg",g="n"),
            A("der","der","の","de la",c="gen",num="sg",g="f"),
            J("deutschen","deutsch","ドイツの","littérature allemande",c="gen",num="sg",g="f"),
            N("Literatur","Literatur","文学","",c="gen",num="sg",g="f"),
            pct("."),
            A("Der","der","その","le",c="nom",num="sg",g="m"),
            N("Gelehrte","Gelehrte","学者","savant",c="nom",num="sg",g="m"),
            N("Faust","Faust","ファウスト","Faust",c="nom",num="sg",g="m"),
            V("schließt","schließen","結ぶ・締結する","conclut",p="3sg"),
            A("einen","ein","一つの","un",c="acc",num="sg",g="m"),
            N("Pakt","Pakt","契約","pacte",c="acc",num="sg",g="m"),
            P("mit","mit","〜と","avec"),
            A("dem","der","その","le",c="dat",num="sg",g="m"),
            N("Teufel","Teufel","悪魔","diable",c="dat",num="sg",g="m"),
            E("Mephistopheles","メフィストフェレス","Méphistophélès"),
            pct(","),
            P("um","um","〜するために","pour"),
            N("Erkenntnis","Erkenntnis","認識・知識","connaissance",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            N("Genuss","Genuss","享楽","plaisir",c="acc",num="sg",g="m"),
            P("zu","zu","〜を",""),
            V("erlangen","erlangen","獲得する","obtenir"),
            pct("."),
            A("Das","das","その","l'",c="nom",num="sg",g="n"),
            N("Werk","Werk","作品","œuvre",c="nom",num="sg",g="n"),
            V("thematisiert","thematisieren","テーマにする","traite de",p="3sg"),
            A("den","der","その","l'",c="acc",num="sg",g="m"),
            J("unstillbaren","unstillbar","止めようのない","insatiable",c="acc",num="sg",g="m"),
            N("Wissensdurst","Wissensdurst","知識への渇望","soif de connaissance",c="acc",num="sg",g="m"),
            A("des","der","の","de l'",c="gen",num="sg",g="m"),
            N("Menschen","Mensch","人間の","homme",c="gen",num="sg",g="m"),
            R("sowie","sowie","また〜も","ainsi que"),
            A("den","der","その","le",c="acc",num="sg",g="m"),
            N("Konflikt","Konflikt","葛藤・対立","conflit",c="acc",num="sg",g="m"),
            P("zwischen","zwischen","〜の間の","entre"),
            N("Streben","Streben","努力・追求","aspiration",c="dat",num="sg",g="n"),
            K("und","und","と","et"),
            N("Verantwortung","Verantwortung","責任","responsabilité",c="dat",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t095",
        "title": "Die deutsche Romantik",
        "subtitle": "Gefühl, Natur und das Geheimnisvolle",
        "level": "B2",
        "category": "Literatur",
        "tokens": [
            A("Die","die","その","le",c="nom",num="sg",g="f"),
            N("Romantik","Romantik","ロマン主義","romantisme",c="nom",num="sg",g="f"),
            V("war","sein","〜であった","était",p="3sg"),
            A("eine","ein","一つの","un",c="nom",num="sg",g="f"),
            J("europäische","europäisch","ヨーロッパの","européen",c="nom",num="sg",g="f"),
            N("Kulturbewegung","Kulturbewegung","文化運動","mouvement culturel",c="nom",num="sg",g="f"),
            A("des","der","の","du début du",c="gen",num="sg",g="n"),
            J("frühen","früh","初期の","début",c="gen",num="sg",g="n"),
            NUM("19.","19","XIX"),
            N("Jahrhunderts","Jahrhundert","世紀の","siècle",c="gen",num="sg",g="n"),
            pct(","),
            A("die","die","その","qui",c="nom",num="sg",g="f"),
            A("das","das","その","le",c="acc",num="sg",g="n"),
            N("Gefühl","Gefühl","感情","sentiment",c="acc",num="sg",g="n"),
            R("über","über","〜を超えて","au-dessus de"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Vernunft","Vernunft","理性","raison",c="acc",num="sg",g="f"),
            V("stellte","stellen","置いた","plaçait",p="3sg"),
            pct("."),
            N("Dichter","Dichter","詩人たち","poètes",c="nom",num="pl",g="m"),
            P("wie","wie","〜のような","comme"),
            E("Novalis","ノヴァーリス","Novalis"),
            K("und","und","と","et"),
            E("Eichendorff","アイヒェンドルフ","Eichendorff"),
            V("verherrlichten","verherrlichen","賛美した","célébraient",p="3pl"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            N("Natur","Natur","自然","nature",c="acc",num="sg",g="f"),
            pct(","),
            A("das","das","その","le",c="acc",num="sg",g="n"),
            N("Mittelalter","Mittelalter","中世","Moyen Âge",c="acc",num="sg",g="n"),
            K("und","und","と","et"),
            A("das","das","その","le",c="acc",num="sg",g="n"),
            N("Geheimnisvolle","Geheimnisvolle","神秘的なもの","mystérieux",c="acc",num="sg",g="n"),
            pct("."),
            Q("Diese","dieser","この","ce",case="nom",number="sg",gender="f"),
            J("literarische","literarisch","文学的な","courant littéraire",c="nom",num="sg",g="f"),
            N("Strömung","Strömung","流れ・潮流","",c="nom",num="sg",g="f"),
            V("entstand","entstehen","生まれた","naquit",p="3sg"),
            P("als","als","〜への","en"),
            N("Reaktion","Reaktion","反応・反発","réaction",c="nom",num="sg",g="f"),
            P("auf","auf","〜に対する","à"),
            A("die","die","その","les",c="acc",num="sg",g="f"),
            N("Aufklärung","Aufklärung","啓蒙主義","Lumières",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            A("die","die","その","l'",c="acc",num="sg",g="f"),
            J("beginnende","beginnend","始まりつつある","naissante",c="acc",num="sg",g="f"),
            N("Industrialisierung","Industrialisierung","工業化","industrialisation",c="acc",num="sg",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t096",
        "title": "Franz Kafka und die Moderne",
        "subtitle": "Entfremdung in der bürokratischen Welt",
        "level": "C1",
        "category": "Literatur",
        "tokens": [
            E("Franz Kafka","フランツ・カフカ","Franz Kafka"),
            V("schildert","schildern","描写する","décrit",p="3sg"),
            P("in","in","〜の中で","dans"),
            Q("seinen","sein","彼の","ses",case="dat",number="pl"),
            N("Werken","Werk","作品","œuvres",c="dat",num="pl",g="n"),
            A("die","die","その","l'",c="acc",num="sg",g="f"),
            N("Entfremdung","Entfremdung","疎外","aliénation",c="acc",num="sg",g="f"),
            A("des","der","の","de l'",c="gen",num="sg",g="n"),
            N("Individuums","Individuum","個人の","individu",c="gen",num="sg",g="n"),
            P("in","in","〜の中で","dans"),
            A("einer","ein","一つの","un",c="dat",num="sg",g="f"),
            J("undurchdringlichen","undurchdringlich","不可解な","impénétrable",c="dat",num="sg",g="f"),
            J("bürokratischen","bürokratisch","官僚的な","bureaucratique",c="dat",num="sg",g="f"),
            N("Welt","Welt","世界","monde",c="dat",num="sg",g="f"),
            pct("."),
            P("In","in","〜の中で","Dans"),
            pct("„"),
            A("Die","die","その","La",c="nom",num="sg",g="f"),
            N("Verwandlung","Verwandlung","変身","Métamorphose",c="nom",num="sg",g="f"),
            pct(chr(8222)),
            V("erwacht","erwachen","目覚める","se réveille",p="3sg"),
            A("der","der","その","le",c="nom",num="sg",g="m"),
            N("Handlungsreisende","Handlungsreisende","外回り営業マン","commis voyageur",c="nom",num="sg",g="m"),
            E("Gregor Samsa","グレーゴル・ザムザ","Gregor Samsa"),
            A("eines","ein","ある","un","c"),
            N("Morgens","Morgen","朝に","matin",c="gen",num="sg",g="m"),
            P("als","als","〜として","en"),
            N("Insekt","Insekt","昆虫・虫","insecte",c="nom",num="sg",g="n"),
            K("und","und","そして","et"),
            V("erlebt","erleben","経験する","vit",p="3sg"),
            Q("seine","sein","彼の","son",case="acc",number="sg",gender="f"),
            J("zunehmende","zunehmend","増大する","croissante",c="acc",num="sg",g="f"),
            N("Isolation","Isolation","孤立","isolation",c="acc",num="sg",g="f"),
            pct("."),
            A("Der","der","その","le",c="nom",num="sg",g="m"),
            N("Begriff","Begriff","概念","terme",c="nom",num="sg",g="m"),
            pct("„"),
            J("kafkaesk","kafkaesk","カフカ的な","kafkaïen"),
            pct(chr(8222)),
            V("bezeichnet","bezeichnen","指す・表す","désigne",p="3sg"),
            R("heute","heute","今日","aujourd'hui"),
            J("absurde","absurd","不条理な","absurdes",c="acc",num="pl"),
            K("und","und","と","et"),
            J("bedrohliche","bedrohlich","脅威的な","menaçantes",c="acc",num="pl"),
            N("Situationen","Situation","状況","situations",c="acc",num="pl",g="f"),
            P("ohne","ohne","〜なしに","sans"),
            J("erkennbaren","erkennbar","認識できる","issue reconnaissable",c="acc",num="sg",g="m"),
            N("Ausweg","Ausweg","出口・逃げ道","",c="acc",num="sg",g="m"),
            pct("."),
        ]
    },

    # ════════════════════════════════════════════════════════════
    # GESELLSCHAFT / POLITIK / WIRTSCHAFT
    # ════════════════════════════════════════════════════════════

    {
        "id": "t097",
        "title": "Die Allgemeine Erklärung der Menschenrechte",
        "subtitle": "Universelle Rechte für alle Menschen",
        "level": "B2",
        "category": "Gesellschaft",
        "tokens": [
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            J("Allgemeine","allgemein","一般的な・普遍的な","Déclaration universelle",c="nom",num="sg",g="f"),
            N("Erklärung","Erklärung","宣言","",c="nom",num="sg",g="f"),
            A("der","der","の","des",c="gen",num="pl"),
            N("Menschenrechte","Menschenrecht","人権","droits de l'homme",c="gen",num="pl",g="n"),
            V("wurde","werden","〜された","fut",p="3sg"),
            P("im","in","〜に","en"),
            N("Jahr","Jahr","年","an",c="dat",num="sg",g="n"),
            NUM("1948","1948年","1948"),
            P("von","von","によって","par"),
            A("der","der","その","l'",c="dat",num="sg",g="f"),
            N("Generalversammlung","Generalversammlung","総会","Assemblée générale",c="dat",num="sg",g="f"),
            A("der","der","の","des",c="gen",num="pl"),
            J("Vereinten","vereint","合一した・連合した","Nations",c="gen",num="pl"),
            N("Nationen","Nation","国連の","Unies",c="gen",num="pl",g="f"),
            V("verabschiedet","verabschieden","採択された","adoptée"),
            pct("."),
            Q("Sie","sie","それは","elle"),
            V("garantiert","garantieren","保証する","garantit",p="3sg"),
            J("grundlegende","grundlegend","基本的な","des droits fondamentaux",c="acc",num="pl"),
            N("Rechte","Recht","権利","",c="acc",num="pl",g="n"),
            P("wie","wie","〜のような","tels que"),
            A("das","das","その","le",c="acc",num="sg",g="n"),
            N("Recht","Recht","権利","droit",c="acc",num="sg",g="n"),
            P("auf","auf","〜に対する","à la"),
            N("Leben","Leben","生命","vie",c="acc",num="sg",g="n"),
            pct(","),
            N("Freiheit","Freiheit","自由","liberté",c="acc",num="sg",g="f"),
            K("und","und","と","et"),
            N("Gedankenfreiheit","Gedankenfreiheit","思想の自由","liberté de pensée",c="acc",num="sg",g="f"),
            P("für","für","のために","pour"),
            J("alle","aller","すべての","tous les",c="acc",num="pl"),
            N("Menschen","Mensch","人間","hommes",c="acc",num="pl",g="m"),
            pct("."),
            Q("Diese","dieser","これらの","ces",case="nom",number="pl"),
            N("Rechte","Recht","権利","droits",c="nom",num="pl",g="n"),
            V("gelten","gelten","適用される","s'appliquent",p="3pl"),
            R("universell","universell","普遍的に","universellement"),
            pct(","),
            R("unabhängig","unabhängig","〜に関わらず","indépendamment"),
            P("von","von","〜から","de la"),
            N("Nationalität","Nationalität","国籍","nationalité",c="dat",num="sg",g="f"),
            pct(","),
            N("Religion","Religion","宗教","religion",c="dat",num="sg",g="f"),
            K("oder","oder","または","ou du"),
            N("Geschlecht","Geschlecht","性別","genre",c="dat",num="sg",g="n"),
            pct("."),
        ]
    },

    {
        "id": "t098",
        "title": "Die Globalisierung",
        "subtitle": "Chancen und Risiken der weltweiten Verflechtung",
        "level": "B2",
        "category": "Wirtschaft",
        "tokens": [
            A("Die","die","その","la",c="nom",num="sg",g="f"),
            N("Globalisierung","Globalisierung","グローバル化","mondialisation",c="nom",num="sg",g="f"),
            V("bezeichnet","bezeichnen","指す・意味する","désigne",p="3sg"),
            A("die","die","その","la",c="acc",num="sg",g="f"),
            J("zunehmende","zunehmend","増大する","croissante",c="acc",num="sg",g="f"),
            J("weltweite","weltweit","世界規模の","mondiale",c="acc",num="sg",g="f"),
            N("Verflechtung","Verflechtung","相互依存・絡み合い","interdépendance",c="acc",num="sg",g="f"),
            P("von","von","の","de l'"),
            N("Wirtschaft","Wirtschaft","経済","économie",c="dat",num="sg",g="f"),
            pct(","),
            N("Kultur","Kultur","文化","culture",c="dat",num="sg",g="f"),
            K("und","und","と","et"),
            N("Politik","Politik","政治","politique",c="dat",num="sg",g="f"),
            P("seit","seit","〜以来","depuis"),
            A("dem","der","その","le",c="dat",num="sg",g="n"),
            NUM("20.","20","XX"),
            N("Jahrhundert","Jahrhundert","世紀","siècle",c="dat",num="sg",g="n"),
            pct("."),
            J("Technologische","technologisch","技術的な","Les innovations technologiques",c="nom",num="pl"),
            N("Innovationen","Innovation","革新・イノベーション","",c="nom",num="pl",g="f"),
            P("in","in","〜の分野での","dans"),
            N("Transport","Transport","輸送","les transports",c="dat",num="sg",g="m"),
            K("und","und","と","et"),
            N("Kommunikation","Kommunikation","通信・コミュニケーション","la communication",c="dat",num="sg",g="f"),
            V("ermöglichten","ermöglichen","可能にした","permirent",p="3pl"),
            A("den","der","その","l'",c="acc",num="sg",g="m"),
            J("rasanten","rasant","急速な","rapide",c="acc",num="sg",g="m"),
            N("Austausch","Austausch","交換・交流","échange",c="acc",num="sg",g="m"),
            P("von","von","の","de"),
            N("Waren","Ware","商品","biens",c="dat",num="pl",g="f"),
            pct(","),
            N("Kapital","Kapital","資本","capitaux",c="dat",num="sg",g="n"),
            K("und","und","と","et"),
            N("Informationen","Information","情報","informations",c="dat",num="pl",g="f"),
            P("über","über","〜を超えて","au-delà des"),
            J("nationale","national","国家の","frontières nationales",c="acc",num="pl"),
            N("Grenzen","Grenze","国境","",c="acc",num="pl",g="f"),
            R("hinaus","hinaus","越えて",""),
            pct("."),
            Q("Diese","dieser","この","ce",case="nom",number="sg",gender="f"),
            N("Entwicklung","Entwicklung","発展","développement",c="nom",num="sg",g="f"),
            V("bietet","bieten","提供する","offre",p="3sg"),
            J("wirtschaftliche","wirtschaftlich","経済的な","des opportunités économiques",c="acc",num="pl"),
            N("Chancen","Chance","チャンス","",c="acc",num="pl",g="f"),
            pct(","),
            V("verschärft","verschärfen","悪化させる","mais exacerbe",p="3sg"),
            R("aber","aber","しかし〜も",""),
            R("auch","auch","また","aussi"),
            J("soziale","sozial","社会的な","des inégalités sociales",c="acc",num="pl"),
            K("und","und","と","et"),
            J("ökologische","ökologisch","生態的な","et écologiques",c="acc",num="pl"),
            N("Ungleichheiten","Ungleichheit","不平等","",c="acc",num="pl",g="f"),
            pct("."),
        ]
    },

    {
        "id": "t099",
        "title": "Der Klimawandel und seine Folgen",
        "subtitle": "Eine globale Herausforderung",
        "level": "B2",
        "category": "Wissenschaft",
        "tokens": [
            P("Seit","seit","〜以来","Depuis"),
            A("der","der","その","l'",c="dat",num="sg",g="f"),
            N("Industrialisierung","Industrialisierung","工業化","industrialisation",c="dat",num="sg",g="f"),
            V("steigt","steigen","上昇する","augmente",p="3sg"),
            A("die","die","その","la",c="nom",num="sg",g="f"),
            N("Konzentration","Konzentration","濃度","concentration",c="nom",num="sg",g="f"),
            P("von","von","の","de"),
            N("Treibhausgasen","Treibhausgas","温室効果ガス","gaz à effet de serre",c="dat",num="pl",g="n"),
            P("in","in","〜の中で","dans"),
            A("der","der","その","l'",c="dat",num="sg",g="f"),
            N("Atmosphäre","Atmosphäre","大気","atmosphère",c="dat",num="sg",g="f"),
            R("kontinuierlich","kontinuierlich","継続的に","continuellement"),
            R("an","an","〜（ansteigen）",""),
            pct("."),
            Q("Dies","dies","これは","cela"),
            V("führt","führen","導く","conduit",p="3sg"),
            P("zur","zu","〜へ","au"),
            N("Erwärmung","Erwärmung","温暖化","réchauffement",c="dat",num="sg",g="f"),
            A("der","der","の","de l'",c="gen",num="sg",g="f"),
            N("Erdatmosphäre","Erdatmosphäre","地球大気","atmosphère terrestre",c="gen",num="sg",g="f"),
            K("und","und","と","et"),
            P("zu","zu","〜へ","à des"),
            J("extremeren","extrem","より極端な","plus extrêmes",c="dat",num="pl"),
            N("Wetterphänomenen","Wetterphänomen","気象現象","phénomènes météorologiques",c="dat",num="pl",g="n"),
            P("wie","wie","〜のような","tels que"),
            N("Dürren","Dürre","干ばつ","sécheresses",c="dat",num="pl",g="f"),
            pct(","),
            N("Überschwemmungen","Überschwemmung","洪水","inondations",c="dat",num="pl",g="f"),
            K("und","und","と","et"),
            J("intensiveren","intensiv","より激しい","tempêtes plus intenses",c="dat",num="pl"),
            N("Stürmen","Sturm","嵐","",c="dat",num="pl",g="m"),
            pct("."),
            A("Das","das","その","l'",c="nom",num="sg",g="n"),
            N("Pariser","pariserisch","パリの","Accord de Paris",c="nom",num="sg",g="n"),
            N("Abkommen","Abkommen","協定","",c="nom",num="sg",g="n"),
            P("von","von","〜の","de"),
            NUM("2015","2015年","2015"),
            V("verpflichtet","verpflichten","義務付ける","engage",p="3sg"),
            A("die","die","その","les",c="acc",num="pl"),
            N("Unterzeichnerstaaten","Unterzeichnerstaat","署名国","États signataires",c="acc",num="pl",g="m"),
            pct(","),
            A("die","die","その","le",c="acc",num="sg",g="f"),
            N("Erderwärmung","Erderwärmung","地球温暖化","réchauffement climatique",c="acc",num="sg",g="f"),
            P("auf","auf","〜以下に","en dessous de"),
            J("unter","unter","〜以下の",""),
            J("zwei","zwei","2の","deux",c="acc",num="sg"),
            N("Grad","Grad","度","degrés",c="acc",num="sg",g="m"),
            N("Celsius","Celsius","摂氏","Celsius",c="acc",num="sg",g="m"),
            P("zu","zu","〜するよう",""),
            V("begrenzen","begrenzen","制限する","limiter"),
            pct("."),
        ]
    },

]  # end NEUE_TEXTE

# ── Nouveaux mots de vocabulaire ──────────────────────────────────────────────

NEUE_WOERTER = [
    {"id":"w1353","lemma":"Revolution","pos":"noun","meaning_ja":"革命","meaning_fr":"révolution","level":"B2"},
    {"id":"w1354","lemma":"Demokratie","pos":"noun","meaning_ja":"民主主義","meaning_fr":"démocratie","level":"B1"},
    {"id":"w1355","lemma":"Monarchie","pos":"noun","meaning_ja":"君主制","meaning_fr":"monarchie","level":"B2"},
    {"id":"w1356","lemma":"Freiheit","pos":"noun","meaning_ja":"自由","meaning_fr":"liberté","level":"A2"},
    {"id":"w1357","lemma":"Gleichheit","pos":"noun","meaning_ja":"平等","meaning_fr":"égalité","level":"B1"},
    {"id":"w1358","lemma":"Aufklärung","pos":"noun","meaning_ja":"啓蒙主義","meaning_fr":"Lumières","level":"C1"},
    {"id":"w1359","lemma":"Vernunft","pos":"noun","meaning_ja":"理性","meaning_fr":"raison","level":"B2"},
    {"id":"w1360","lemma":"Imperativ","pos":"noun","meaning_ja":"命令・命法","meaning_fr":"impératif","level":"C1"},
    {"id":"w1361","lemma":"Maxime","pos":"noun","meaning_ja":"格率・行動原則","meaning_fr":"maxime","level":"C1"},
    {"id":"w1362","lemma":"Ethik","pos":"noun","meaning_ja":"倫理学","meaning_fr":"éthique","level":"B2"},
    {"id":"w1363","lemma":"Übermenschen","pos":"noun","meaning_ja":"超人","meaning_fr":"surhomme","level":"C1"},
    {"id":"w1364","lemma":"Wille","pos":"noun","meaning_ja":"意志","meaning_fr":"volonté","level":"B2"},
    {"id":"w1365","lemma":"Idee","pos":"noun","meaning_ja":"イデア・理念","meaning_fr":"idée","level":"A2"},
    {"id":"w1366","lemma":"Erkenntnis","pos":"noun","meaning_ja":"認識・知識","meaning_fr":"connaissance","level":"B2"},
    {"id":"w1367","lemma":"Existenz","pos":"noun","meaning_ja":"実存・存在","meaning_fr":"existence","level":"B2"},
    {"id":"w1368","lemma":"Essenz","pos":"noun","meaning_ja":"本質","meaning_fr":"essence","level":"C1"},
    {"id":"w1369","lemma":"Atom","pos":"noun","meaning_ja":"原子","meaning_fr":"atome","level":"B1"},
    {"id":"w1370","lemma":"Proton","pos":"noun","meaning_ja":"陽子","meaning_fr":"proton","level":"B2"},
    {"id":"w1371","lemma":"Elektron","pos":"noun","meaning_ja":"電子","meaning_fr":"électron","level":"B2"},
    {"id":"w1372","lemma":"Ordnungszahl","pos":"noun","meaning_ja":"原子番号","meaning_fr":"numéro atomique","level":"B2"},
    {"id":"w1373","lemma":"Valenzelektron","pos":"noun","meaning_ja":"価電子","meaning_fr":"électron de valence","level":"C1"},
    {"id":"w1374","lemma":"Verbrennung","pos":"noun","meaning_ja":"燃焼","meaning_fr":"combustion","level":"B2"},
    {"id":"w1375","lemma":"Oxidation","pos":"noun","meaning_ja":"酸化","meaning_fr":"oxydation","level":"B2"},
    {"id":"w1376","lemma":"Reaktion","pos":"noun","meaning_ja":"反応","meaning_fr":"réaction","level":"B1"},
    {"id":"w1377","lemma":"Relativitätstheorie","pos":"noun","meaning_ja":"相対性理論","meaning_fr":"théorie de la relativité","level":"C1"},
    {"id":"w1378","lemma":"Kernspaltung","pos":"noun","meaning_ja":"核分裂","meaning_fr":"fission nucléaire","level":"C1"},
    {"id":"w1379","lemma":"Fotosynthese","pos":"noun","meaning_ja":"光合成","meaning_fr":"photosynthèse","level":"B1"},
    {"id":"w1380","lemma":"Chlorophyll","pos":"noun","meaning_ja":"葉緑素","meaning_fr":"chlorophylle","level":"B2"},
    {"id":"w1381","lemma":"Kohlendioxid","pos":"noun","meaning_ja":"二酸化炭素","meaning_fr":"dioxyde de carbone","level":"B1"},
    {"id":"w1382","lemma":"Sauerstoff","pos":"noun","meaning_ja":"酸素","meaning_fr":"oxygène","level":"A2"},
    {"id":"w1383","lemma":"Kohlenstoffkreislauf","pos":"noun","meaning_ja":"炭素循環","meaning_fr":"cycle du carbone","level":"C1"},
    {"id":"w1384","lemma":"Wissensdurst","pos":"noun","meaning_ja":"知識への渇望","meaning_fr":"soif de connaissance","level":"C1"},
    {"id":"w1385","lemma":"Entfremdung","pos":"noun","meaning_ja":"疎外","meaning_fr":"aliénation","level":"C1"},
    {"id":"w1386","lemma":"Bürokratie","pos":"noun","meaning_ja":"官僚制","meaning_fr":"bureaucratie","level":"B2"},
    {"id":"w1387","lemma":"Menschenrecht","pos":"noun","meaning_ja":"人権","meaning_fr":"droit de l'homme","level":"B1"},
    {"id":"w1388","lemma":"Globalisierung","pos":"noun","meaning_ja":"グローバル化","meaning_fr":"mondialisation","level":"B1"},
    {"id":"w1389","lemma":"Verflechtung","pos":"noun","meaning_ja":"相互依存・絡み合い","meaning_fr":"interdépendance","level":"C1"},
    {"id":"w1390","lemma":"Treibhausgas","pos":"noun","meaning_ja":"温室効果ガス","meaning_fr":"gaz à effet de serre","level":"B2"},
    {"id":"w1391","lemma":"Erderwärmung","pos":"noun","meaning_ja":"地球温暖化","meaning_fr":"réchauffement climatique","level":"B1"},
    {"id":"w1392","lemma":"Aufstieg","pos":"noun","meaning_ja":"台頭・上昇","meaning_fr":"montée","level":"B2"},
    {"id":"w1393","lemma":"Scheitern","pos":"noun","meaning_ja":"失敗・崩壊","meaning_fr":"échec","level":"B2"},
    {"id":"w1394","lemma":"Kapitulation","pos":"noun","meaning_ja":"降伏","meaning_fr":"capitulation","level":"B2"},
    {"id":"w1395","lemma":"Wiedervereinigung","pos":"noun","meaning_ja":"再統一","meaning_fr":"réunification","level":"B1"},
    {"id":"w1396","lemma":"Romantik","pos":"noun","meaning_ja":"ロマン主義","meaning_fr":"romantisme","level":"B2"},
    {"id":"w1397","lemma":"Pakt","pos":"noun","meaning_ja":"契約・盟約","meaning_fr":"pacte","level":"B2"},
    {"id":"w1398","lemma":"Herausforderung","pos":"noun","meaning_ja":"課題・挑戦","meaning_fr":"défi","level":"B2"},
    {"id":"w1399","lemma":"verändern","pos":"verb","meaning_ja":"変える","meaning_fr":"changer","level":"A2"},
    {"id":"w1400","lemma":"beeinflussen","pos":"verb","meaning_ja":"影響を与える","meaning_fr":"influencer","level":"B2"},
    {"id":"w1401","lemma":"entwickeln","pos":"verb","meaning_ja":"発展させる・開発する","meaning_fr":"développer","level":"B1"},
    {"id":"w1402","lemma":"entstehen","pos":"verb","meaning_ja":"生じる・生まれる","meaning_fr":"naître","level":"B1"},
    {"id":"w1403","lemma":"thematisieren","pos":"verb","meaning_ja":"テーマにする","meaning_fr":"traiter de","level":"C1"},
    {"id":"w1404","lemma":"proklamieren","pos":"verb","meaning_ja":"宣言する","meaning_fr":"proclamer","level":"C1"},
    {"id":"w1405","lemma":"regulieren","pos":"verb","meaning_ja":"調節する","meaning_fr":"réguler","level":"B2"},
    {"id":"w1406","lemma":"verpflichten","pos":"verb","meaning_ja":"義務付ける","meaning_fr":"obliger","level":"B2"},
    {"id":"w1407","lemma":"begrenzen","pos":"verb","meaning_ja":"制限する","meaning_fr":"limiter","level":"B2"},
    {"id":"w1408","lemma":"kategorisch","pos":"adjective","meaning_ja":"定言的な・断固とした","meaning_fr":"catégorique","level":"C1"},
    {"id":"w1409","lemma":"universell","pos":"adjective","meaning_ja":"普遍的な","meaning_fr":"universel","level":"B2"},
    {"id":"w1410","lemma":"exotherm","pos":"adjective","meaning_ja":"発熱の","meaning_fr":"exothermique","level":"C1"},
    {"id":"w1411","lemma":"endotherm","pos":"adjective","meaning_ja":"吸熱の","meaning_fr":"endothermique","level":"C1"},
    {"id":"w1412","lemma":"biochemisch","pos":"adjective","meaning_ja":"生化学的な","meaning_fr":"biochimique","level":"C1"},
    {"id":"w1413","lemma":"kontinuierlich","pos":"adverb","meaning_ja":"継続的に","meaning_fr":"continuellement","level":"B2"},
    {"id":"w1414","lemma":"grundlegend","pos":"adverb","meaning_ja":"根本的に","meaning_fr":"fondamentalement","level":"B2"},
    {"id":"w1415","lemma":"nachhaltig","pos":"adverb","meaning_ja":"持続的に・深く","meaning_fr":"durablement","level":"B2"},
]

# ── Mise à jour des fichiers ──────────────────────────────────────────────────

def main():
    # Textes
    with open(TEXTS_PATH, encoding='utf-8') as f:
        texts_data = json.load(f)

    existing_ids = {t['id'] for t in texts_data['texts']}
    added_texts = 0
    for t in NEUE_TEXTE:
        if t['id'] not in existing_ids:
            texts_data['texts'].append(t)
            added_texts += 1

    texts_data['meta']['total'] = len(texts_data['texts'])

    with open(TEXTS_PATH, 'w', encoding='utf-8') as f:
        json.dump(texts_data, f, ensure_ascii=False, indent=2)
    print(f"✓ テキスト追加: {added_texts}件 → 合計 {len(texts_data['texts'])}件")

    # Vocabulaire
    with open(VOCAB_PATH, encoding='utf-8') as f:
        vocab_data = json.load(f)

    existing_lemmas = {w['lemma'] for w in vocab_data['words']}
    added_vocab = 0
    for w in NEUE_WOERTER:
        if w['lemma'] not in existing_lemmas:
            vocab_data['words'].append(w)
            added_vocab += 1

    vocab_data['meta']['total'] = len(vocab_data['words'])

    with open(VOCAB_PATH, 'w', encoding='utf-8') as f:
        json.dump(vocab_data, f, ensure_ascii=False, indent=2)
    print(f"✓ 語彙追加: {added_vocab}件 → 合計 {len(vocab_data['words'])}件")

if __name__ == '__main__':
    main()
